<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Infragistics.SamplesBrowser</RootNamespace>
    <AssemblyName>Infragistics.SamplesBrowser</AssemblyName>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ApplicationIcon>Images\Icons\SamplesBrowser_WPF.ico</ApplicationIcon>
    <PreBuildEvent>taskkill /f /fi "pid gt 0" /im Infragistics.SamplesBrowser.exe</PreBuildEvent>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
    <OutputPath>..\Output\</OutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <OutputPath>bin\DebugWPF\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
    <CodeAnalysisLogFile>bin\DebugWPF\Infragistics.SamplesBrowser.exe.CodeAnalysisLog.xml</CodeAnalysisLogFile>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisRuleSetDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\\Rule Sets</CodeAnalysisRuleSetDirectories>
    <CodeAnalysisIgnoreBuiltInRuleSets>false</CodeAnalysisIgnoreBuiltInRuleSets>
    <CodeAnalysisRuleDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\FxCop\\Rules</CodeAnalysisRuleDirectories>
    <CodeAnalysisIgnoreBuiltInRules>false</CodeAnalysisIgnoreBuiltInRules>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>bin\DebugWPF\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
    <CodeAnalysisLogFile>bin\DebugWPF\Infragistics.SamplesBrowser.exe.CodeAnalysisLog.xml</CodeAnalysisLogFile>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisRuleSetDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\\Rule Sets</CodeAnalysisRuleSetDirectories>
    <CodeAnalysisIgnoreBuiltInRuleSets>false</CodeAnalysisIgnoreBuiltInRuleSets>
    <CodeAnalysisRuleDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\FxCop\\Rules</CodeAnalysisRuleDirectories>
    <CodeAnalysisIgnoreBuiltInRules>false</CodeAnalysisIgnoreBuiltInRules>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DefineConstants>TRACE;WPF</DefineConstants>
    <DebugType>false</DebugType>
    <CodeAnalysisLogFile>bin\Release\Infragistics.SamplesBrowser.exe.CodeAnalysisLog.xml</CodeAnalysisLogFile>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisRuleSetDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\\Rule Sets</CodeAnalysisRuleSetDirectories>
    <CodeAnalysisIgnoreBuiltInRuleSets>true</CodeAnalysisIgnoreBuiltInRuleSets>
    <CodeAnalysisRuleDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\FxCop\\Rules</CodeAnalysisRuleDirectories>
    <CodeAnalysisIgnoreBuiltInRules>true</CodeAnalysisIgnoreBuiltInRules>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DefineConstants>TRACE;WPF</DefineConstants>
    <DebugType>false</DebugType>
    <CodeAnalysisLogFile>bin\Release\Infragistics.SamplesBrowser.exe.CodeAnalysisLog.xml</CodeAnalysisLogFile>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisRuleSetDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\\Rule Sets</CodeAnalysisRuleSetDirectories>
    <CodeAnalysisIgnoreBuiltInRuleSets>true</CodeAnalysisIgnoreBuiltInRuleSets>
    <CodeAnalysisRuleDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\FxCop\\Rules</CodeAnalysisRuleDirectories>
    <CodeAnalysisIgnoreBuiltInRules>true</CodeAnalysisIgnoreBuiltInRules>
  </PropertyGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
    <None Update="TableOfContentsCrossShema.xsd">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\SamplesBrowser_WPF.ico" />
    <Resource Include="Images\Shell\FeatureBrowserBackground.png" />
    <Resource Include="Images\WelcomePage\SamplesHomeWPF.png" />
    <Resource Include="Images\WelcomePage\shadow.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="BuildScripts.txt" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.0,Profile=Client">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4 Client Profile %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Windows.Installer.3.1">
      <Visible>False</Visible>
      <ProductName>Windows Installer 3.1</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="TableOfContents.xml">
      <SubType>Designer</SubType>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Images\LandingPages\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IGBarcodeReader\IGBarcodeReader.WPF.csproj" />
    <ProjectReference Include="..\IGBarcode\IGBarcode.WPF.csproj" />
    <ProjectReference Include="..\IGBusyIndicator\IGBusyIndicator.WPF.csproj" />
    <ProjectReference Include="..\IGCalculationManager\IGCalculationManager.WPF.csproj" />
    <ProjectReference Include="..\IGCalendar\IGCalendar.WPF.csproj" />
    <ProjectReference Include="..\IGCarouselListBox\IGCarouselListBox.WPF.csproj" />
    <ProjectReference Include="..\IGCarouselPanel\IGCarouselPanel.WPF.csproj" />
    <ProjectReference Include="..\IGCategoryChart\IGCategoryChart.WPF.csproj" />
    <ProjectReference Include="..\IGColorPicker\IGColorPicker.WPF.csproj" />
    <ProjectReference Include="..\IGComboEditor\IGComboEditor.WPF.csproj" />
    <ProjectReference Include="..\IGContextMenu\IGContextMenu.WPF.csproj" />
    <ProjectReference Include="..\IGDashboardTile\IGDashboardTile.csproj" />
    <ProjectReference Include="..\IGDataCards\IGDataCards.WPF.csproj" />
    <ProjectReference Include="..\IGDataCarousel\IGDataCarousel.WPF.csproj" />
    <ProjectReference Include="..\IGDataChart\IGDataChart.WPF.csproj" />
    <ProjectReference Include="..\IGDataGrid\IGDataGrid.WPF.csproj" />
    <ProjectReference Include="..\IGDataPresenter\IGDataPresenter.WPF.csproj" />
    <ProjectReference Include="..\IGDataTree\IGDataTree.WPF.csproj" />
    <ProjectReference Include="..\IGDiagram\IGDiagram.WPF.csproj" />
    <ProjectReference Include="..\IGDialogWindow\IGDialogWindow.WPF.csproj" />
    <ProjectReference Include="..\IGDockManager\IGDockManager.WPF.csproj" />
    <ProjectReference Include="..\IGDoughnutChart\IGDoughnutChart.WPF.csproj" />
    <ProjectReference Include="..\IGDragDropFramework\IGDragDropFramework.WPF.csproj" />
    <ProjectReference Include="..\IGEditors\IGEditors.WPF.csproj" />
    <ProjectReference Include="..\IGExcel\IGExcel.WPF.csproj" />
    <ProjectReference Include="..\IGFinancialChart\IGFinancialChart.csproj" />
    <ProjectReference Include="..\IGFormulaEditor\IGFormulaEditor.WPF.csproj" />
    <ProjectReference Include="..\IGFunnelChart\IGFunnelChart.WPF.csproj" />
    <ProjectReference Include="..\IGGantt\IGGantt.WPF.csproj" />
    <ProjectReference Include="..\IGGeographicMap\IGGeographicMap.WPF.csproj" />
    <ProjectReference Include="..\IGLinearGauge\IGLinearGauge.WPF.csproj" />
    <ProjectReference Include="..\IGMap\IGMap.WPF.csproj" />
    <ProjectReference Include="..\IGMath\IGMath.WPF.csproj" />
    <ProjectReference Include="..\IGMenu\IGMenu.WPF.csproj" />
    <ProjectReference Include="..\IGMonthCalendar\IGMonthCalendar.WPF.csproj" />
    <ProjectReference Include="..\IGMultiColumnComboEditor\IGMultiColumnComboEditor.WPF.csproj" />
    <ProjectReference Include="..\IGNetworkNode\IGNetworkNode.WPF.csproj" />
    <ProjectReference Include="..\IGBulletGraph\IGBulletGraph.WPF.csproj" />
    <ProjectReference Include="..\IGOrgChart\IGOrgChart.WPF.csproj" />
    <ProjectReference Include="..\IGOutlookBar\IGOutlookBar.WPF.csproj" />
    <ProjectReference Include="..\IGPersistenceFramework\IGPersistenceFramework.WPF.csproj" />
    <ProjectReference Include="..\IGPieChart\IGPieChart.WPF.csproj" />
    <ProjectReference Include="..\IGPivotGrid\IGPivotGrid.WPF.csproj" />
    <ProjectReference Include="..\IGPropertyGrid\IGPropertyGrid.WPF.csproj" />
    <ProjectReference Include="..\IGRadialGauge\IGRadialGauge.WPF.csproj" />
    <ProjectReference Include="..\IGRadialMenu\IGRadialMenu.WPF.csproj" />
    <ProjectReference Include="..\IGReporting\IGReporting.WPF.csproj" />
    <ProjectReference Include="..\IGResourceWasher\IGResourceWasher.WPF.csproj" />
    <ProjectReference Include="..\IGRibbon\IGRibbon.WPF.csproj" />
    <ProjectReference Include="..\IGRichTextEditor\IGRichTextEditor.WPF.csproj" />
    <ProjectReference Include="..\IGSchedule\IGSchedule.WPF.csproj" />
    <ProjectReference Include="..\IGShapeChart\IGShapeChart.csproj" />
    <ProjectReference Include="..\IGSlider\IGSlider.WPF.csproj" />
    <ProjectReference Include="..\IGSparkline\IGSparkline.WPF.csproj" />
    <ProjectReference Include="..\IGSpellChecker\IGSpellChecker.WPF.csproj" />
    <ProjectReference Include="..\IGSpreadsheet\IGSpreadsheet.WPF.csproj" />
    <ProjectReference Include="..\IGSurfaceChart\IGSurfaceChart.WPF.csproj" />
    <ProjectReference Include="..\IGSyntaxEditor\IGSyntaxEditor.WPF.csproj" />
    <ProjectReference Include="..\IGSyntaxParsingEngine\IGSyntaxParsingEngine.WPF.csproj" />
    <ProjectReference Include="..\IGTabControl\IGTabControl.WPF.csproj" />
    <ProjectReference Include="..\IGTagCloud\IGTagCloud.WPF.csproj" />
    <ProjectReference Include="..\IGThemeManager\IGThemeManager.WPF.csproj" />
    <ProjectReference Include="..\IGTileManager\IGTileManager.WPF.csproj" />
    <ProjectReference Include="..\IGTimeline\IGTimeline.WPF.csproj" />
    <ProjectReference Include="..\IGToolbar\IGToolbar.WPF.csproj" />
    <ProjectReference Include="..\IGTreeGrid\IGTreeGrid.WPF.csproj" />
    <ProjectReference Include="..\IGTreemap\IGTreemap.WPF.csproj" />
    <ProjectReference Include="..\IGUndoRedoFramework\IGUndoRedoFramework.WPF.csproj" />
    <ProjectReference Include="..\IGWord\IGWord.WPF.csproj" />
    <ProjectReference Include="..\IGZoombar\IGZoombar.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Assets\Infragistics.Samples.Assets.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Services\Infragistics.Samples.Services.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGBarcode.png" />
    <Resource Include="Images\Icons\IGBarcodeReader.png" />
    <Resource Include="Images\Icons\IGBulletGraph.png" />
    <Resource Include="Images\Icons\IGCalculationManager.png" />
    <Resource Include="Images\Icons\IGCalendar.png" />
    <Resource Include="Images\Icons\IGColorPicker.png" />
    <Resource Include="Images\Icons\IGComboEditor.png" />
    <Resource Include="Images\Icons\IGCompression.png" />
    <Resource Include="Images\Icons\IGContextMenu.png" />
    <Resource Include="Images\Icons\IGDataChart.png" />
    <Resource Include="Images\Icons\IGDataTree.png" />
    <Resource Include="Images\Icons\IGDatePicker.png" />
    <Resource Include="Images\Icons\IGDialogWindow.png" />
    <Resource Include="Images\Icons\IGDockManager.png" />
    <Resource Include="Images\Icons\IGDragDropFramework.png" />
    <Resource Include="Images\Icons\IGEditors.png" />
    <Resource Include="Images\Icons\IGExcel.png" />
    <Resource Include="Images\Icons\IGFormulaEditor.png" />
    <Resource Include="Images\Icons\IGFunnelChart.png" />
    <Resource Include="Images\Icons\IGGauge.png" />
    <Resource Include="Images\Icons\IGGeographicMap.png" />
    <Resource Include="Images\Icons\IGGrid.png" />
    <Resource Include="Images\Icons\IGHtmlViewer.png" />
    <Resource Include="Images\Icons\IGInputs.png" />
    <Resource Include="Images\Icons\IGMap.png" />
    <Resource Include="Images\Icons\IGMath.png" />
    <Resource Include="Images\Icons\IGMathLibrary.png" />
    <Resource Include="Images\Icons\IGMenu.png" />
    <Resource Include="Images\Icons\IGMultiColumnCombo.png" />
    <Resource Include="Images\Icons\IGNetworkNode.png" />
    <Resource Include="Images\Icons\IGOrgChart.png" />
    <Resource Include="Images\Icons\IGOutlookBar.png" />
    <Resource Include="Images\Icons\IGPersistenceFramework.png" />
    <Resource Include="Images\Icons\IGPieChart.png" />
    <Resource Include="Images\Icons\IGPivotGrid.png" />
    <Resource Include="Images\Icons\IGResourceWasher.png" />
    <Resource Include="Images\Icons\IGRibbon.png" />
    <Resource Include="Images\Icons\IGSchedule.png" />
    <Resource Include="Images\Icons\IGSlider.png" />
    <Resource Include="Images\Icons\IGSparkline.png" />
    <Resource Include="Images\Icons\IGSpellChecker.png" />
    <Resource Include="Images\Icons\IGTagCloud.png" />
    <Resource Include="Images\Icons\IGTileManager.png" />
    <Resource Include="Images\Icons\IGTileView.png" />
    <Resource Include="Images\Icons\IGTimeline.png" />
    <Resource Include="Images\Icons\IGTree.png" />
    <Resource Include="Images\Icons\IGTreemap.png" />
    <Resource Include="Images\Icons\IGVirtualCollection.png" />
    <Resource Include="Images\Icons\IGWebChart.png" />
    <Resource Include="Images\Icons\IGWord.png" />
    <Resource Include="Images\Icons\IGZoombar.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGCarouselListbox.png" />
    <Resource Include="Images\Icons\IGCarouselPanel.png" />
    <Resource Include="Images\Icons\IGDataCards.png" />
    <Resource Include="Images\Icons\IGDataCarousel.png" />
    <Resource Include="Images\Icons\IGDataGrid.png" />
    <Resource Include="Images\Icons\IGDataPresenter.png" />
    <Resource Include="Images\Icons\IGMonthCalendar.png" />
    <Resource Include="Images\Icons\IGReporting.png" />
    <Resource Include="Images\Icons\IGTabControl.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGUndoRedo.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGGantt.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGSyntaxEditor.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGSyntaxParsingEngine.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGDoughnutChart.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGRadialGauge.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Shell\WpfNavigationLogo.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGRichTextEditor.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGLinearGauge.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Shell\introLogo.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGSegmentedDisplay.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGRadialMenu.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGDiagram.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGPropertyGrid.png" />
    <Resource Include="Images\Icons\IGSpreadsheet.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGThemeManager.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGTreeGrid.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGBusyIndicator.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGSurfaceChart.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGCategoryChart.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGShapeChart.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\WelcomePage\WelcomePageLogo.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGScatterChart.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGFinancialChart.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Icons\IGToolbar.png" />
  </ItemGroup>
</Project>