<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>IGSpreadsheet</RootNamespace>
    <AssemblyName>IGSpreadsheet</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>DEBUG;TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>DEBUG;TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Infragistics.WPF.Charts.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.DataVisualization.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Documents.Core.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Editors.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Excel.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Menus.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Ribbon.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Spreadsheet.Charts.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Spreadsheet.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Undo.Trial" Version="25.2.24" />
    <PackageReference Include="System.Runtime.Serialization.Formatters" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Files\en\Sample1.xlsx" />
    <Resource Include="Files\en\Sample2.xlsx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Bold.png" />
    <Resource Include="Images\HAlignCenter.png" />
    <Resource Include="Images\EditCopy.png" />
    <Resource Include="Images\EditCut.png" />
    <Resource Include="Images\EditRedo.png" />
    <Resource Include="Images\EditUndo.png" />
    <Resource Include="Images\Italic.png" />
    <Resource Include="Images\HAlignLeft.png" />
    <Resource Include="Images\Paste_16x16.png" />
    <Resource Include="Images\Paste_32x32.png" />
    <Resource Include="Images\HAlignRight.png" />
    <Resource Include="Images\Underline.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\VAlignBottom.png" />
    <Resource Include="Images\VAlignCenter.png" />
    <Resource Include="Images\VAlignTop.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Open_Large.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Zoom100-32x32.png" />
    <Resource Include="Images\Zoom32x32.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\FreezeFirstColumn_32x32.png" />
    <Resource Include="Images\FreezePanes_32x32.png" />
    <Resource Include="Images\FreezeTopRow_32x32.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Hide.png" />
    <Resource Include="Images\Split.png" />
    <Resource Include="Images\Unhide.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\ZoomToSel-32x32.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MergeCellsAcross.png" />
    <Resource Include="Images\MergeCellsAndCenter.png" />
    <Resource Include="Images\MergeCells.png" />
    <Resource Include="Images\Strikethrough.png" />
    <Resource Include="Images\UnmergeCells.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\FontDec.png" />
    <Resource Include="Images\FontInc.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\IndentDec.png" />
    <Resource Include="Images\IndentInc.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Files\ja\Sample1.xlsx" />
    <Resource Include="Files\ja\Sample2.xlsx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Files\en\browsers.jpg" />
    <Resource Include="Files\ja\browsers.jpg" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\ProtectSheet.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\ProtectWorkbook.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\DoubleUnderline.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Files\en\ConditionalFormatData.xlsx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Files\en\Sample3.xlsx" />
    <Resource Include="Files\ja\Sample3.xlsx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Files\ja\ConditionalFormatData.xlsx" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Samples\Filtering\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Files\en\CustomSort.xlsx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Files\ja\CustomSort.xlsx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Files\en\ChartData.xlsx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Files\ja\ChartData.xlsx" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
</Project>