//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGShowcase.FinanceDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGShowcase.FinanceDashboard.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Finance Dashboard is an interactive application demonstrating the capabilities of Infragistics Financial Chart control applied to the Financial Services industry. The Stock Chart view of the application is built using the Financial Chart, which has been optimized for high speed financial charting. The Financial Chart supports multiple datasets with millions of data points and real time updates. In addition, this control enables key statistical and technical indicators as well as comparisons to key compe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AppInfo {
            get {
                return ResourceManager.GetString("AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Finance Dashboard is an interactive application demonstrating the capabilities of Infragistics Data Chart and Tree Map controls applied to the Financial Services industry. The Stock Chart view of the application is built using the Data Chart, which has been optimized for high speed financial charting.  The Data Chart supports large datasets with millions of data points and real time updates.  In addition, this control enables key statistical and technical indicators as well as comparisons to key competi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AppInfoOLD {
            get {
                return ResourceManager.GetString("AppInfoOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string AppLanguage {
            get {
                return ResourceManager.GetString("AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINANCE STOCK DASHBOARD.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISUALIZING CHANGES OF FINANCIAL STOCK VALUES.
        /// </summary>
        public static string AppSubTitle {
            get {
                return ResourceManager.GetString("AppSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AppView_About {
            get {
                return ResourceManager.GetString("AppView_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Map.
        /// </summary>
        public static string AppView_Heat_Map {
            get {
                return ResourceManager.GetString("AppView_Heat_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks Chart.
        /// </summary>
        public static string AppView_Stocks_Chart {
            get {
                return ResourceManager.GetString("AppView_Stocks_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on an Industry node to view it&apos;s child companies.
        /// </summary>
        public static string Company_Summary_Info {
            get {
                return ResourceManager.GetString("Company_Summary_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Range.
        /// </summary>
        public static string DataColumn_AnualRange {
            get {
                return ResourceManager.GetString("DataColumn_AnualRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string DataColumn_Ask {
            get {
                return ResourceManager.GetString("DataColumn_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid.
        /// </summary>
        public static string DataColumn_Bid {
            get {
                return ResourceManager.GetString("DataColumn_Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change %.
        /// </summary>
        public static string DataColumn_Change {
            get {
                return ResourceManager.GetString("DataColumn_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily High.
        /// </summary>
        public static string DataColumn_Daily_High {
            get {
                return ResourceManager.GetString("DataColumn_Daily_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Low.
        /// </summary>
        public static string DataColumn_Daily_Low {
            get {
                return ResourceManager.GetString("DataColumn_Daily_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Range.
        /// </summary>
        public static string DataColumn_DailyRange {
            get {
                return ResourceManager.GetString("DataColumn_DailyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div. Yield %.
        /// </summary>
        public static string DataColumn_Div_Yield {
            get {
                return ResourceManager.GetString("DataColumn_Div_Yield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBITA.
        /// </summary>
        public static string DataColumn_EBITA {
            get {
                return ResourceManager.GetString("DataColumn_EBITA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPS.
        /// </summary>
        public static string DataColumn_EPS {
            get {
                return ResourceManager.GetString("DataColumn_EPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mkt Cap.
        /// </summary>
        public static string DataColumn_Market_Cap {
            get {
                return ResourceManager.GetString("DataColumn_Market_Cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Profit Margin.
        /// </summary>
        public static string DataColumn_Net_Profit_Margin {
            get {
                return ResourceManager.GetString("DataColumn_Net_Profit_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string DataColumn_Open {
            get {
                return ResourceManager.GetString("DataColumn_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P/E.
        /// </summary>
        public static string DataColumn_P_E {
            get {
                return ResourceManager.GetString("DataColumn_P_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price to Book Value (mrq).
        /// </summary>
        public static string DataColumn_Price_to_Book {
            get {
                return ResourceManager.GetString("DataColumn_Price_to_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price to Free Cash Flow (mrq).
        /// </summary>
        public static string DataColumn_Price_to_Free_Cash_Flow {
            get {
                return ResourceManager.GetString("DataColumn_Price_to_Free_Cash_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROE %.
        /// </summary>
        public static string DataColumn_ROE {
            get {
                return ResourceManager.GetString("DataColumn_ROE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string DataColumn_Vol {
            get {
                return ResourceManager.GetString("DataColumn_Vol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Profit
        ///Margin.
        /// </summary>
        public static string Grid_Net_Profit_Margin {
            get {
                return ResourceManager.GetString("Grid_Net_Profit_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price to Book
        ///Value (mrq).
        /// </summary>
        public static string Grid_Price_to_Book {
            get {
                return ResourceManager.GetString("Grid_Price_to_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price to Free
        ///Cash Flow (mrq).
        /// </summary>
        public static string Grid_Price_to_Free_Cash_Flow {
            get {
                return ResourceManager.GetString("Grid_Price_to_Free_Cash_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string HeatMap_Filter {
            get {
                return ResourceManager.GetString("HeatMap_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Map.
        /// </summary>
        public static string HeatMap_Title {
            get {
                return ResourceManager.GetString("HeatMap_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-click on a black Sector node to drill down and right-click to go back..
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Market.
        /// </summary>
        public static string Market_Description {
            get {
                return ResourceManager.GetString("Market_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string Please_Wait {
            get {
                return ResourceManager.GetString("Please_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Over Time.
        /// </summary>
        public static string Price_Over_Time {
            get {
                return ResourceManager.GetString("Price_Over_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Volume.
        /// </summary>
        public static string Sales_Volume {
            get {
                return ResourceManager.GetString("Sales_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock is not trading on the market anymore!.
        /// </summary>
        public static string Stock_DataIsMissing {
            get {
                return ResourceManager.GetString("Stock_DataIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Price.
        /// </summary>
        public static string Stock_Price {
            get {
                return ResourceManager.GetString("Stock_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Stock Symbol or Name.
        /// </summary>
        public static string Type_Ticker_Here {
            get {
                return ResourceManager.GetString("Type_Ticker_Here", resourceCulture);
            }
        }
    }
}
