<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>IGDiagram</RootNamespace>
    <AssemblyName>IGDiagram</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>DEBUG;TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>DEBUG;TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Infragistics.WPF.ColorPicker.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Controls.Editors.XamMaskedInput.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.DataVisualization.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Diagram.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.DragDrop.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Editors.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Ribbon.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Slider.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Undo.Trial" Version="25.2.24" />
    <PackageReference Include="System.Runtime.Serialization.Formatters" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Samples\Localization\" />
    <Folder Include="Samples\Navigation\" />
    <Folder Include="Samples\Performance\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Assets\Infragistics.Samples.Assets.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Edit32.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Settings32.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Delete32.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Copy32.png" />
    <Resource Include="Images\Paste32.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Cut32.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\SelectAll64.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Redo32.png" />
    <Resource Include="Images\Undo32.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\ClassIcon.png" />
    <Resource Include="Images\entityKey.png" />
    <Resource Include="Images\NavigationProperty_24.bmp" />
    <Resource Include="Images\properties_16xLG.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\bring-forward.png" />
    <Resource Include="Images\bring-to-front.png" />
    <Resource Include="Images\connector.png" />
    <Resource Include="Images\Pan.png" />
    <Resource Include="Images\pointer-tool.png" />
    <Resource Include="Images\send-backward.png" />
    <Resource Include="Images\send-to-back.png" />
    <Resource Include="Images\Zoom.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\cross.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\none.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\always.png" />
    <Resource Include="Images\auto.png" />
    <Resource Include="Images\hover.png" />
    <Resource Include="Images\never.png" />
  </ItemGroup>
</Project>