//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleBrowserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleBrowserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SampleBrowserResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Samples.
        /// </summary>
        internal static string Application_Samples {
            get {
                return ResourceManager.GetString("Application_Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string Code_View_FontSize_Large_String {
            get {
                return ResourceManager.GetString("Code_View_FontSize_Large_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Code_View_FontSize_Medium_String {
            get {
                return ResourceManager.GetString("Code_View_FontSize_Medium_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string Code_View_FontSize_Small_String {
            get {
                return ResourceManager.GetString("Code_View_FontSize_Small_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size:.
        /// </summary>
        internal static string Code_View_FontSize_String {
            get {
                return ResourceManager.GetString("Code_View_FontSize_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lines of code.
        /// </summary>
        internal static string Code_View_LinesOfCode_String {
            get {
                return ResourceManager.GetString("Code_View_LinesOfCode_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop Out Code View.
        /// </summary>
        internal static string Code_View_PopOutCodeView_String {
            get {
                return ResourceManager.GetString("Code_View_PopOutCodeView_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Code_View_SelectAll_String {
            get {
                return ResourceManager.GetString("Code_View_SelectAll_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code View.
        /// </summary>
        internal static string Code_View_String {
            get {
                return ResourceManager.GetString("Code_View_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no! We`ve encounterd an unexpected error..
        /// </summary>
        internal static string ErrorPage_Header {
            get {
                return ResourceManager.GetString("ErrorPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh this page.
        /// </summary>
        internal static string ErrorPage_Options1 {
            get {
                return ResourceManager.GetString("ErrorPage_Options1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit the back button to return to the previous page.
        /// </summary>
        internal static string ErrorPage_Options2 {
            get {
                return ResourceManager.GetString("ErrorPage_Options2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are two things you can do to resolve the error:.
        /// </summary>
        internal static string ErrorPage_Options_Message {
            get {
                return ResourceManager.GetString("ErrorPage_Options_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re sorry, but we have encountered an unexpected error while processing your request.
        ///If this problem persists, please let us know..
        /// </summary>
        internal static string ErrorPage_SubHeader {
            get {
                return ResourceManager.GetString("ErrorPage_SubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppps an error occurred.
        /// </summary>
        internal static string ErrorPage_Title {
            get {
                return ResourceManager.GetString("ErrorPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Controls.
        /// </summary>
        internal static string Featured_Controls {
            get {
                return ResourceManager.GetString("Featured_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features List.
        /// </summary>
        internal static string FeaturesList_String {
            get {
                return ResourceManager.GetString("FeaturesList_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features &amp;amp; Samples.
        /// </summary>
        internal static string Features_and_samples_String {
            get {
                return ResourceManager.GetString("Features_and_samples_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features:.
        /// </summary>
        internal static string Features_String {
            get {
                return ResourceManager.GetString("Features_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Features.
        /// </summary>
        internal static string KeyFeatures_String {
            get {
                return ResourceManager.GetString("KeyFeatures_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Left_Nav_Search_Text {
            get {
                return ResourceManager.GetString("Left_Nav_Search_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New / Updated Features.
        /// </summary>
        internal static string New_Updated_Features_String {
            get {
                return ResourceManager.GetString("New_Updated_Features_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a problem with your Silverlight browser plugin. Please make sure it&apos;s enabled and allowed. If you don&apos;t have Silverlight installed yet, please install it. It won&apos;t hurt you. :).
        /// </summary>
        internal static string NonSilverlightInstalledMessage_String {
            get {
                return ResourceManager.GetString("NonSilverlightInstalledMessage_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path : .
        /// </summary>
        internal static string Select_Sample_File_Path_String {
            get {
                return ResourceManager.GetString("Select_Sample_File_Path_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sample source file to View.
        /// </summary>
        internal static string Select_Sample_String {
            get {
                return ResourceManager.GetString("Select_Sample_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sample browser requires Microsoft SQL Server Express installed and running on your machine.  If you do not have Microsoft SQL Express you can download the software from the &lt;a href=&quot;http://www.microsoft.com/Sqlserver/2005/en/us/express.aspx&quot; target=&quot;_blank&quot;&gt;Microsoft site&lt;/a&gt;.  Here is an additional link to &lt;a href=&quot;http://msdn.microsoft.com/en-us/library/ms143722(SQL.90).aspx&quot; target=&quot;_blank&quot;&gt;installation instructions&lt;/a&gt; for Microsoft SQL Express ..
        /// </summary>
        internal static string SQLServer_Paragraph1 {
            get {
                return ResourceManager.GetString("SQLServer_Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will now need to add the necessary security and roles to this database..
        /// </summary>
        internal static string SQLServer_Paragraph13 {
            get {
                return ResourceManager.GetString("SQLServer_Paragraph13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have Microsoft SQL Server Express installed, but still having problems?.
        /// </summary>
        internal static string SQLServer_Paragraph2 {
            get {
                return ResourceManager.GetString("SQLServer_Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that an instance of SQL Express is installed and running.  Check the Services dialog in Task Manager and check for an instance of SQL Server Express.  The default process name is MSSQL$SQLEXPRESS..
        /// </summary>
        internal static string SQLServer_Paragraph3 {
            get {
                return ResourceManager.GetString("SQLServer_Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next launch the SQL Server Surface Area Configuation application.  This tool can be found at Start -&gt; Programs - &gt; SQL Server 2005 (or 2008) -&gt; Configuration Tools -&gt; SQL Server Configuration Manager.  Using this tool you can ensure that the Startup type is set to Automatic for the Database Engine and SQL Server Browser.  You can also manage Remote Connections settings using this tool..
        /// </summary>
        internal static string SQLServer_Paragraph4 {
            get {
                return ResourceManager.GetString("SQLServer_Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure that your local firewall is not blocking SQL Server Express..
        /// </summary>
        internal static string SQLServer_Paragraph5 {
            get {
                return ResourceManager.GetString("SQLServer_Paragraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t install Microsoft SQL Server Express, but have access to a Microsoft SQL Server instance?.
        /// </summary>
        internal static string SQLServer_Paragraph6 {
            get {
                return ResourceManager.GetString("SQLServer_Paragraph6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open SQL Server Management Studio and connect to SQL Server..
        /// </summary>
        internal static string SQLServer_Paragraph8 {
            get {
                return ResourceManager.GetString("SQLServer_Paragraph8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand the tree in Object Expolorer until you see the Database node..
        /// </summary>
        internal static string SQLServer_Paragraph9 {
            get {
                return ResourceManager.GetString("SQLServer_Paragraph9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft SQL Server required.
        /// </summary>
        internal static string SQLServer_Title {
            get {
                return ResourceManager.GetString("SQLServer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls &amp; Application Samples.
        /// </summary>
        internal static string TopNavControlHeaderString {
            get {
                return ResourceManager.GetString("TopNavControlHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string TopNavControlMaximize {
            get {
                return ResourceManager.GetString("TopNavControlMaximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string TopNavControlMinimize {
            get {
                return ResourceManager.GetString("TopNavControlMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string TopNavControl_ControlsTitle {
            get {
                return ResourceManager.GetString("TopNavControl_ControlsTitle", resourceCulture);
            }
        }
    }
}
