//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgOutlook.Modules.Mail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IgOutlook.Modules.Mail.Resources.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A to Z.
        /// </summary>
        public static string AtoZ_Text {
            get {
                return ResourceManager.GetString("AtoZ_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string By_Text {
            get {
                return ResourceManager.GetString("By_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category_Text {
            get {
                return ResourceManager.GetString("Category_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date_Text {
            get {
                return ResourceManager.GetString("Date_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Text {
            get {
                return ResourceManager.GetString("Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string Flags_Text {
            get {
                return ResourceManager.GetString("Flags_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From_Text {
            get {
                return ResourceManager.GetString("From_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High_Text {
            get {
                return ResourceManager.GetString("High_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string HomeTab_Header_Home {
            get {
                return ResourceManager.GetString("HomeTab_Header_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string HomeTab_RibbonGroupCaption_Delete {
            get {
                return ResourceManager.GetString("HomeTab_RibbonGroupCaption_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string HomeTab_RibbonGroupCaption_New {
            get {
                return ResourceManager.GetString("HomeTab_RibbonGroupCaption_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond.
        /// </summary>
        public static string HomeTab_RibbonGroupCaption_Respond {
            get {
                return ResourceManager.GetString("HomeTab_RibbonGroupCaption_Respond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string HomeTab_RibbonGroupCaption_Tags {
            get {
                return ResourceManager.GetString("HomeTab_RibbonGroupCaption_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string HomeTab_RibbonGroupDelete_ButtonTool_Delete {
            get {
                return ResourceManager.GetString("HomeTab_RibbonGroupDelete_ButtonTool_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Email.
        /// </summary>
        public static string HomeTab_RibbonGroupNew_ButtonTool_NewEmail {
            get {
                return ResourceManager.GetString("HomeTab_RibbonGroupNew_ButtonTool_NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string HomeTab_RibbonGroupRespond_ButtonTool_Forward {
            get {
                return ResourceManager.GetString("HomeTab_RibbonGroupRespond_ButtonTool_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string HomeTab_RibbonGroupRespond_ButtonTool_Reply {
            get {
                return ResourceManager.GetString("HomeTab_RibbonGroupRespond_ButtonTool_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply All.
        /// </summary>
        public static string HomeTab_RibbonGroupRespond_ButtonTool_ReplyAll {
            get {
                return ResourceManager.GetString("HomeTab_RibbonGroupRespond_ButtonTool_ReplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorize.
        /// </summary>
        public static string HomeTab_RibbonGroupTags_ButtonTool_Categorize {
            get {
                return ResourceManager.GetString("HomeTab_RibbonGroupTags_ButtonTool_Categorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up.
        /// </summary>
        public static string HomeTab_RibbonGroupTags_ButtonTool_FollowUp {
            get {
                return ResourceManager.GetString("HomeTab_RibbonGroupTags_ButtonTool_FollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread\Read.
        /// </summary>
        public static string HomeTab_RibbonGroupTags_ButtonTool_UnreadRead {
            get {
                return ResourceManager.GetString("HomeTab_RibbonGroupTags_ButtonTool_UnreadRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importance.
        /// </summary>
        public static string Importance_Text {
            get {
                return ResourceManager.GetString("Importance_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Later_Text {
            get {
                return ResourceManager.GetString("Later_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low_Text {
            get {
                return ResourceManager.GetString("Low_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Items.
        /// </summary>
        public static string MailGroup_DeletedItems_Text {
            get {
                return ResourceManager.GetString("MailGroup_DeletedItems_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafts.
        /// </summary>
        public static string MailGroup_Drafts_Text {
            get {
                return ResourceManager.GetString("MailGroup_Drafts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string MailGroup_Inbox_Text {
            get {
                return ResourceManager.GetString("MailGroup_Inbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Folders.
        /// </summary>
        public static string MailGroup_PersonalFolders_Text {
            get {
                return ResourceManager.GetString("MailGroup_PersonalFolders_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Items.
        /// </summary>
        public static string MailGroup_SentItems_Text {
            get {
                return ResourceManager.GetString("MailGroup_SentItems_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail State.
        /// </summary>
        public static string MailState_Text {
            get {
                return ResourceManager.GetString("MailState_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cc.
        /// </summary>
        public static string Message_Cc_Text {
            get {
                return ResourceManager.GetString("Message_Cc_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Message_Send_Text {
            get {
                return ResourceManager.GetString("Message_Send_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Message_Subject_Text {
            get {
                return ResourceManager.GetString("Message_Subject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message_Text {
            get {
                return ResourceManager.GetString("Message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Message_To_Text {
            get {
                return ResourceManager.GetString("Message_To_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string MessageHomeTab_RibbonGroupCaption_Clipboard {
            get {
                return ResourceManager.GetString("MessageHomeTab_RibbonGroupCaption_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string MessageHomeTab_RibbonGroupCaption_Font {
            get {
                return ResourceManager.GetString("MessageHomeTab_RibbonGroupCaption_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        public static string MessageHomeTab_RibbonGroupCaption_Paragraph {
            get {
                return ResourceManager.GetString("MessageHomeTab_RibbonGroupCaption_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string MessageHomeTab_RibbonGroupCaption_Tags {
            get {
                return ResourceManager.GetString("MessageHomeTab_RibbonGroupCaption_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string MessageHomeTab_RibbonGroupNew_ButtonTool_Copy {
            get {
                return ResourceManager.GetString("MessageHomeTab_RibbonGroupNew_ButtonTool_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string MessageHomeTab_RibbonGroupNew_ButtonTool_Cut {
            get {
                return ResourceManager.GetString("MessageHomeTab_RibbonGroupNew_ButtonTool_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string MessageHomeTab_RibbonGroupNew_ButtonTool_Paste {
            get {
                return ResourceManager.GetString("MessageHomeTab_RibbonGroupNew_ButtonTool_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Importance.
        /// </summary>
        public static string MessageHomeTab_RibbonGroupTags_ButtonTool_HighImportance {
            get {
                return ResourceManager.GetString("MessageHomeTab_RibbonGroupTags_ButtonTool_HighImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Importance.
        /// </summary>
        public static string MessageHomeTab_RibbonGroupTags_ButtonTool_LowImportance {
            get {
                return ResourceManager.GetString("MessageHomeTab_RibbonGroupTags_ButtonTool_LowImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message not found..
        /// </summary>
        public static string MessageNotFound_Message {
            get {
                return ResourceManager.GetString("MessageNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message has not been sent. Do you want to close?.
        /// </summary>
        public static string MessageNotSent_Message {
            get {
                return ResourceManager.GetString("MessageNotSent_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff1\deff0\stshfdbch0\stshfloch31506\stshfhich31506\stshfbi31506\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs1025{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
        ///{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}{\flomajor\f31500\fb [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MessageReplyTemplate {
            get {
                return ResourceManager.GetString("MessageReplyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff1\deff0\stshfdbch0\stshfloch31506\stshfhich31506\stshfbi31506\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs1025{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
        ///{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}{\flomajor\f31500\fb [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MessageReplyWithCcTemplate {
            get {
                return ResourceManager.GetString("MessageReplyWithCcTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string Newest_Text {
            get {
                return ResourceManager.GetString("Newest_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to davids@demo.infragistics.com.
        /// </summary>
        public static string NewMessageSenderEmail {
            get {
                return ResourceManager.GetString("NewMessageSenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string Oldest_Text {
            get {
                return ResourceManager.GetString("Oldest_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string OutlookBarGroup_Header_Mail {
            get {
                return ResourceManager.GetString("OutlookBarGroup_Header_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Red_Text {
            get {
                return ResourceManager.GetString("Red_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_Text {
            get {
                return ResourceManager.GetString("Search_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject_Text {
            get {
                return ResourceManager.GetString("Subject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today_Text {
            get {
                return ResourceManager.GetString("Today_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread.
        /// </summary>
        public static string Unred_Text {
            get {
                return ResourceManager.GetString("Unred_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string Untitled_Text {
            get {
                return ResourceManager.GetString("Untitled_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z to A.
        /// </summary>
        public static string ZtoA_Text {
            get {
                return ResourceManager.GetString("ZtoA_Text", resourceCulture);
            }
        }
    }
}
