//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGPieChart.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PieChartStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public PieChartStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGPieChart.Resources.PieChartStrings", typeof(PieChartStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string XPC_Black {
            get {
                return ResourceManager.GetString("XPC_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string XPC_Blue {
            get {
                return ResourceManager.GetString("XPC_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string XPC_Brown {
            get {
                return ResourceManager.GetString("XPC_Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold Category.
        /// </summary>
        public static string XPC_Category_Threshold {
            get {
                return ResourceManager.GetString("XPC_Category_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkGray.
        /// </summary>
        public static string XPC_DarkGray {
            get {
                return ResourceManager.GetString("XPC_DarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string XPC_Green {
            get {
                return ResourceManager.GetString("XPC_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Label Color.
        /// </summary>
        public static string XPC_InnerLabel {
            get {
                return ResourceManager.GetString("XPC_InnerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels Displayed.
        /// </summary>
        public static string XPC_Labels_Displayed {
            get {
                return ResourceManager.GetString("XPC_Labels_Displayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels Position.
        /// </summary>
        public static string XPC_Labels_Poistion {
            get {
                return ResourceManager.GetString("XPC_Labels_Poistion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightGray.
        /// </summary>
        public static string XPC_LightGray {
            get {
                return ResourceManager.GetString("XPC_LightGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        public static string XPC_Magenta {
            get {
                return ResourceManager.GetString("XPC_Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string XPC_Orange {
            get {
                return ResourceManager.GetString("XPC_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string XPC_Others {
            get {
                return ResourceManager.GetString("XPC_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer Label Color.
        /// </summary>
        public static string XPC_OuterLabel {
            get {
                return ResourceManager.GetString("XPC_OuterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string XPC_Percent {
            get {
                return ResourceManager.GetString("XPC_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string XPC_Purple {
            get {
                return ResourceManager.GetString("XPC_Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string XPC_Red {
            get {
                return ResourceManager.GetString("XPC_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string XPC_Text {
            get {
                return ResourceManager.GetString("XPC_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string XPC_Values {
            get {
                return ResourceManager.GetString("XPC_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string XPC_White {
            get {
                return ResourceManager.GetString("XPC_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string XPC_Yellow {
            get {
                return ResourceManager.GetString("XPC_Yellow", resourceCulture);
            }
        }
    }
}
