//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGMenu.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MenuStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGMenu.Resources.MenuStrings", typeof(MenuStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string XWM_AddRemoveDisable_Add {
            get {
                return ResourceManager.GetString("XWM_AddRemoveDisable_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Item.
        /// </summary>
        public static string XWM_AddRemoveDisable_AddNewItem {
            get {
                return ResourceManager.GetString("XWM_AddRemoveDisable_AddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string XWM_AddRemoveDisable_Disable {
            get {
                return ResourceManager.GetString("XWM_AddRemoveDisable_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 1.
        /// </summary>
        public static string XWM_AddRemoveDisable_MenuItem1 {
            get {
                return ResourceManager.GetString("XWM_AddRemoveDisable_MenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 2.
        /// </summary>
        public static string XWM_AddRemoveDisable_MenuItem2 {
            get {
                return ResourceManager.GetString("XWM_AddRemoveDisable_MenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 3.
        /// </summary>
        public static string XWM_AddRemoveDisable_MenuItem3 {
            get {
                return ResourceManager.GetString("XWM_AddRemoveDisable_MenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 4.
        /// </summary>
        public static string XWM_AddRemoveDisable_MenuItem4 {
            get {
                return ResourceManager.GetString("XWM_AddRemoveDisable_MenuItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 5.
        /// </summary>
        public static string XWM_AddRemoveDisable_MenuItem5 {
            get {
                return ResourceManager.GetString("XWM_AddRemoveDisable_MenuItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 6.
        /// </summary>
        public static string XWM_AddRemoveDisable_MenuItem6 {
            get {
                return ResourceManager.GetString("XWM_AddRemoveDisable_MenuItem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 7.
        /// </summary>
        public static string XWM_AddRemoveDisable_MenuItem7 {
            get {
                return ResourceManager.GetString("XWM_AddRemoveDisable_MenuItem7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newly-added item.
        /// </summary>
        public static string XWM_AddRemoveDisable_NewlyAddedItem {
            get {
                return ResourceManager.GetString("XWM_AddRemoveDisable_NewlyAddedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string XWM_AddRemoveDisable_Remove {
            get {
                return ResourceManager.GetString("XWM_AddRemoveDisable_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string XWM_Close {
            get {
                return ResourceManager.GetString("XWM_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string XWM_Copy {
            get {
                return ResourceManager.GetString("XWM_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string XWM_Cut {
            get {
                return ResourceManager.GetString("XWM_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string XWM_Edit {
            get {
                return ResourceManager.GetString("XWM_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand on Hover.
        /// </summary>
        public static string XWM_EnableExpansionBehavior {
            get {
                return ResourceManager.GetString("XWM_EnableExpansionBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string XWM_File {
            get {
                return ResourceManager.GetString("XWM_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion Behavior.
        /// </summary>
        public static string XWM_MenuExpansion {
            get {
                return ResourceManager.GetString("XWM_MenuExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string XWM_New {
            get {
                return ResourceManager.GetString("XWM_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string XWM_Open {
            get {
                return ResourceManager.GetString("XWM_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string XWM_Paste {
            get {
                return ResourceManager.GetString("XWM_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string XWM_Project {
            get {
                return ResourceManager.GetString("XWM_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string XWM_Save {
            get {
                return ResourceManager.GetString("XWM_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string XWM_Solution {
            get {
                return ResourceManager.GetString("XWM_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User options file.
        /// </summary>
        public static string XWM_UserOption {
            get {
                return ResourceManager.GetString("XWM_UserOption", resourceCulture);
            }
        }
    }
}
