<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>IGDockManager</RootNamespace>
    <AssemblyName>IGDockManager</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <PackageReference Include="Infragistics.WPF.DockManager.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Trial" Version="25.1.117" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\CustomGlyphs.png" />
    <Resource Include="Images\CustomizingContentPaneContextMenu.png" />
    <Resource Include="Images\CustomizingTabGroupFilesMenu.png" />
    <Resource Include="Images\DIDisable.png" />
    <Resource Include="Images\DIDrag.png" />
    <Resource Include="Images\DropPreview.png" />
    <Resource Include="Images\error.png" />
    <Resource Include="Images\folder_16x16.png" />
    <Resource Include="Images\FontColor.png" />
    <Resource Include="Images\history.png" />
    <Resource Include="Images\IconsContentPanes.png" />
    <Resource Include="Images\output.png" />
    <Resource Include="Images\properties.png" />
    <Resource Include="Images\save_16x16.png" />
    <Resource Include="Images\SettingTheTheme.png" />
    <Resource Include="Images\solution_explorer.png" />
    <Resource Include="Images\team_explorer.png" />
  </ItemGroup>
</Project>