<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>IGSpellChecker</RootNamespace>
    <AssemblyName>IGSpellChecker</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Infragistics.WPF.DialogWindow.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.SpellChecker.Trial" Version="25.2.24" />
    <PackageReference Include="System.Runtime.Serialization.Formatters" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Flags\Australia.png" />
    <Resource Include="Images\Flags\flag_Canada.jpg" />
    <Resource Include="Images\Flags\flag_Canada.png" />
    <Resource Include="Images\Flags\flag_Germany.jpg" />
    <Resource Include="Images\Flags\flag_Germany.png" />
    <Resource Include="Images\Flags\flag_Italy.jpg" />
    <Resource Include="Images\Flags\flag_Italy.png" />
    <Resource Include="Images\Flags\flag_USA.jpg" />
    <Resource Include="Images\Flags\flag_USA.png" />
    <Resource Include="Images\Flags\France.png" />
    <Resource Include="Images\Flags\Germany.png" />
    <Resource Include="Images\Flags\GreatBritain.png" />
    <Resource Include="Images\Flags\Netherlands.png" />
    <Resource Include="Images\Flags\Portugal.png" />
    <Resource Include="Images\Flags\Spain.png" />
    <Resource Include="Images\Flags\USFlag.png" />
  </ItemGroup>
</Project>