<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>IGGantt</RootNamespace>
    <AssemblyName>IGGantt</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>DEBUG;TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Infragistics.WPF.Calendar.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Controls.Grids.XamGrid.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.DataManager.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Editors.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Gantt.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Menus.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Ribbon.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Schedules.Trial" Version="25.1.117" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Samples\Localization\" />
    <Folder Include="Samples\Navigation\" />
    <Folder Include="Samples\Performance\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\mode.png" />
    <Resource Include="Images\task.png" />
    <Resource Include="Images\outdent_16x16.png" />
    <Resource Include="Images\indent_16x16.png" />
    <Resource Include="Images\respectlinks_16x16.png" />
    <Resource Include="Images\inactivate_16x16.png" />
    <Resource Include="Images\minus_16x16.png" />
    <Resource Include="Images\plus_16x16.png" />
    <Resource Include="Images\newTask_32x32.png" />
    <Resource Include="Images\deleteTask_32x32.png" />
    <Resource Include="Images\calculate_32x32.png" />
    <Resource Include="Images\deleteLink_16x16.png" />
    <Resource Include="Images\auto_32x32.png" />
    <Resource Include="Images\manual_32x32.png" />
    <Resource Include="Images\outline_32x32.png" />
    <Resource Include="Images\open_32x32.png" />
    <Resource Include="Images\defaultApplicationIcon.png" />
    <Resource Include="Images\outdent_32x32.png" />
    <Resource Include="Images\indent_32x32.png" />
    <Resource Include="Images\scrollBackward_32x32.png" />
    <Resource Include="Images\scrollForward_32x32.png" />
    <Resource Include="Images\clearSort_32x32.png" />
    <Resource Include="Images\timeline_marker32.png" />
    <Resource Include="Images\zoom32.png" />
    <Resource Include="Images\date32.png" />
  </ItemGroup>
</Project>