//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGShapeChart.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShapeChartStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ShapeChartStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGShapeChart.Resources.ShapeChartStrings", typeof(ShapeChartStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length (in feet).
        /// </summary>
        public static string XW_AirplaneLength {
            get {
                return ResourceManager.GetString("XW_AirplaneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (in feet).
        /// </summary>
        public static string XW_AirplaneWidth {
            get {
                return ResourceManager.GetString("XW_AirplaneWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string XW_Alignment {
            get {
                return ResourceManager.GetString("XW_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Major Interval.
        /// </summary>
        public static string XW_AxisIntervals_Hide_Major {
            get {
                return ResourceManager.GetString("XW_AxisIntervals_Hide_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Minor Interval.
        /// </summary>
        public static string XW_AxisIntervals_Hide_Minor {
            get {
                return ResourceManager.GetString("XW_AxisIntervals_Hide_Minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Interval Options.
        /// </summary>
        public static string XW_AxisIntervals_Options {
            get {
                return ResourceManager.GetString("XW_AxisIntervals_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment is applied only if Labels have Angle property set to zero.
        /// </summary>
        public static string XW_AxisLabels_AlignmentTooltip {
            get {
                return ResourceManager.GetString("XW_AxisLabels_AlignmentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string XW_AxisLabels_Angle {
            get {
                return ResourceManager.GetString("XW_AxisLabels_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extent.
        /// </summary>
        public static string XW_AxisLabels_Extent {
            get {
                return ResourceManager.GetString("XW_AxisLabels_Extent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        public static string XW_AxisLabels_Margin {
            get {
                return ResourceManager.GetString("XW_AxisLabels_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Label Options.
        /// </summary>
        public static string XW_AxisLabels_Options {
            get {
                return ResourceManager.GetString("XW_AxisLabels_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAxis Labels.
        /// </summary>
        public static string XW_AxisLabels_ShowXAxisLabels {
            get {
                return ResourceManager.GetString("XW_AxisLabels_ShowXAxisLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAxis Labels.
        /// </summary>
        public static string XW_AxisLabels_ShowYAxisLabels {
            get {
                return ResourceManager.GetString("XW_AxisLabels_ShowYAxisLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Interval.
        /// </summary>
        public static string XW_AxisMajorInterval {
            get {
                return ResourceManager.GetString("XW_AxisMajorInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Thickness.
        /// </summary>
        public static string XW_AxisMajorStrokeThickness {
            get {
                return ResourceManager.GetString("XW_AxisMajorStrokeThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Maximum.
        /// </summary>
        public static string XW_AxisMaximumValue {
            get {
                return ResourceManager.GetString("XW_AxisMaximumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Minimum.
        /// </summary>
        public static string XW_AxisMinimumValue {
            get {
                return ResourceManager.GetString("XW_AxisMinimumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Interval.
        /// </summary>
        public static string XW_AxisMinorInterval {
            get {
                return ResourceManager.GetString("XW_AxisMinorInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Thickness.
        /// </summary>
        public static string XW_AxisMinorStrokeThickness {
            get {
                return ResourceManager.GetString("XW_AxisMinorStrokeThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Max.
        /// </summary>
        public static string XW_AxisRangeMax {
            get {
                return ResourceManager.GetString("XW_AxisRangeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Min.
        /// </summary>
        public static string XW_AxisRangeMin {
            get {
                return ResourceManager.GetString("XW_AxisRangeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Title Options.
        /// </summary>
        public static string XW_AxisTitle_Options {
            get {
                return ResourceManager.GetString("XW_AxisTitle_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Even.
        /// </summary>
        public static string XW_BreakEven {
            get {
                return ResourceManager.GetString("XW_BreakEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Sales 2017.
        /// </summary>
        public static string XW_BreakEven_Title {
            get {
                return ResourceManager.GetString("XW_BreakEven_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHART TYPE.
        /// </summary>
        public static string XW_ChartType {
            get {
                return ResourceManager.GetString("XW_ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Types:.
        /// </summary>
        public static string XW_ChartTypes_Available {
            get {
                return ResourceManager.GetString("XW_ChartTypes_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Type Options.
        /// </summary>
        public static string XW_ChartTypes_Options {
            get {
                return ResourceManager.GetString("XW_ChartTypes_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the different chart types that XamShapeChart supports.
        /// </summary>
        public static string XW_ChartTypes_Subtitle {
            get {
                return ResourceManager.GetString("XW_ChartTypes_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Types.
        /// </summary>
        public static string XW_ChartTypes_Title {
            get {
                return ResourceManager.GetString("XW_ChartTypes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string XW_Cities {
            get {
                return ResourceManager.GetString("XW_Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA TYPE.
        /// </summary>
        public static string XW_DataType {
            get {
                return ResourceManager.GetString("XW_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Cost.
        /// </summary>
        public static string XW_FixedCost {
            get {
                return ResourceManager.GetString("XW_FixedCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1}m.
        /// </summary>
        public static string XW_FloorPlan_LabelFormat {
            get {
                return ResourceManager.GetString("XW_FloorPlan_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units are in meters (m).
        /// </summary>
        public static string XW_FloorPlan_Subtitle {
            get {
                return ResourceManager.GetString("XW_FloorPlan_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Floor Plan.
        /// </summary>
        public static string XW_FloorPlan_Title {
            get {
                return ResourceManager.GetString("XW_FloorPlan_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string XW_FontSize {
            get {
                return ResourceManager.GetString("XW_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Style.
        /// </summary>
        public static string XW_FontStyle {
            get {
                return ResourceManager.GetString("XW_FontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Weight.
        /// </summary>
        public static string XW_FontWeight {
            get {
                return ResourceManager.GetString("XW_FontWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        public static string XW_Foreground {
            get {
                return ResourceManager.GetString("XW_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string XW_Legend {
            get {
                return ResourceManager.GetString("XW_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss Area.
        /// </summary>
        public static string XW_LossArea {
            get {
                return ResourceManager.GetString("XW_LossArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marginal Area.
        /// </summary>
        public static string XW_MarginalArea {
            get {
                return ResourceManager.GetString("XW_MarginalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marginal Profit.
        /// </summary>
        public static string XW_MarginalProfit {
            get {
                return ResourceManager.GetString("XW_MarginalProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin of Safety.
        /// </summary>
        public static string XW_MarginOfSafety {
            get {
                return ResourceManager.GetString("XW_MarginOfSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price ($).
        /// </summary>
        public static string XW_Price_Title {
            get {
                return ResourceManager.GetString("XW_Price_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Area.
        /// </summary>
        public static string XW_ProfitArea {
            get {
                return ResourceManager.GetString("XW_ProfitArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string XW_Regions {
            get {
                return ResourceManager.GetString("XW_Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Revenue.
        /// </summary>
        public static string XW_SalesRevenue {
            get {
                return ResourceManager.GetString("XW_SalesRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string XW_Title_Alignment {
            get {
                return ResourceManager.GetString("XW_Title_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        public static string XW_Title_Margin {
            get {
                return ResourceManager.GetString("XW_Title_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string XW_Title_Rotation {
            get {
                return ResourceManager.GetString("XW_Title_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string XW_TotalCost {
            get {
                return ResourceManager.GetString("XW_TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Units.
        /// </summary>
        public static string XW_Units_Title {
            get {
                return ResourceManager.GetString("XW_Units_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Cost.
        /// </summary>
        public static string XW_VariableCost {
            get {
                return ResourceManager.GetString("XW_VariableCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Axis.
        /// </summary>
        public static string XW_XAxis {
            get {
                return ResourceManager.GetString("XW_XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Axis.
        /// </summary>
        public static string XW_YAxis {
            get {
                return ResourceManager.GetString("XW_YAxis", resourceCulture);
            }
        }
    }
}
