//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGDialogWindow.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogWindowStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public DialogWindowStrings()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGDialogWindow.Resources.DialogWindowStrings", typeof(DialogWindowStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ConfigurationPanel_Header_Options {
            get {
                return ResourceManager.GetString("ConfigurationPanel_Header_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Window.
        /// </summary>
        public static string XDW_ContainerWindow {
            get {
                return ResourceManager.GetString("XDW_ContainerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close button enabled.
        /// </summary>
        public static string XDW_ControlButtons_CloseEnabled {
            get {
                return ResourceManager.GetString("XDW_ControlButtons_CloseEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Icon enabled.
        /// </summary>
        public static string XDW_ControlButtons_HeaderIconEnabled {
            get {
                return ResourceManager.GetString("XDW_ControlButtons_HeaderIconEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize button enabled.
        /// </summary>
        public static string XDW_ControlButtons_MaximizeEnabled {
            get {
                return ResourceManager.GetString("XDW_ControlButtons_MaximizeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize button enabled.
        /// </summary>
        public static string XDW_ControlButtons_MinimizeEnabled {
            get {
                return ResourceManager.GetString("XDW_ControlButtons_MinimizeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Window Style.
        /// </summary>
        public static string XDW_CustomStyledWindow {
            get {
                return ResourceManager.GetString("XDW_CustomStyledWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string XDW_Down {
            get {
                return ResourceManager.GetString("XDW_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaunchWindow.
        /// </summary>
        public static string XDW_LaunchWindow {
            get {
                return ResourceManager.GetString("XDW_LaunchWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string XDW_Left {
            get {
                return ResourceManager.GetString("XDW_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the left container.
        /// </summary>
        public static string XDW_LeftContainer {
            get {
                return ResourceManager.GetString("XDW_LeftContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You closed the prompt message box.
        /// </summary>
        public static string XDW_MessageBox_Closed {
            get {
                return ResourceManager.GetString("XDW_MessageBox_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have just accepted the prompt.
        /// </summary>
        public static string XDW_MessageBox_OK {
            get {
                return ResourceManager.GetString("XDW_MessageBox_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string XDW_Right {
            get {
                return ResourceManager.GetString("XDW_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the right container.
        /// </summary>
        public static string XDW_RightContainer {
            get {
                return ResourceManager.GetString("XDW_RightContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string XDW_ShowDialog_ButtonCancel {
            get {
                return ResourceManager.GetString("XDW_ShowDialog_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string XDW_ShowDialog_ButtonOK {
            get {
                return ResourceManager.GetString("XDW_ShowDialog_ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Dialog in Container.
        /// </summary>
        public static string XDW_ShowDialog_Container {
            get {
                return ResourceManager.GetString("XDW_ShowDialog_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Message Box dialog.
        /// </summary>
        public static string XDW_ShowDialog_MessageBox {
            get {
                return ResourceManager.GetString("XDW_ShowDialog_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Dialog.
        /// </summary>
        public static string XDW_ShowDialog_Plain {
            get {
                return ResourceManager.GetString("XDW_ShowDialog_Plain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        public static string XDW_ShowDialog_Prompt {
            get {
                return ResourceManager.GetString("XDW_ShowDialog_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Dialog with Blur Modal Background Effect.
        /// </summary>
        public static string XDW_ShowModalDialogWithBlurEffect {
            get {
                return ResourceManager.GetString("XDW_ShowModalDialogWithBlurEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string XDW_Up {
            get {
                return ResourceManager.GetString("XDW_Up", resourceCulture);
            }
        }
    }
}
