<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>IGGeographicMap</RootNamespace>
    <AssemblyName>IGGeographicMap</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Infragistics.WPF.Charts.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.ColorPicker.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.DataVisualization.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.DialogWindow.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.GeographicMap.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Slider.Trial" Version="25.2.24" />
    <PackageReference Include="CoreWCF.Primitives" Version="1.8.0" />
    <PackageReference Include="CoreWCF.ConfigurationManager" Version="1.8.0" />
    <PackageReference Include="CoreWCF.Http" Version="1.8.0" />
    <PackageReference Include="CoreWCF.WebHttp" Version="1.8.0" />
    <PackageReference Include="CoreWCF.NetTcp" Version="1.8.0" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Assets\Infragistics.Samples.Assets.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Services\Infragistics.Samples.Services.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\licenses.licx" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\Models\" />
    <Folder Include="Shapefiles\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\AzureDarkGrey.png" />
    <Resource Include="Resources\AzureHybridRoad.png" />
    <Resource Include="Resources\AzureImagery.png" />
    <Resource Include="Resources\AzureRoad.png" />
    <Resource Include="Resources\AzureTrafficAndRoad.png" />
    <Resource Include="Resources\AzureWeatherInfraredRoad.png" />
    <Resource Include="Resources\BingAerial.png" />
    <Resource Include="Resources\BingAerialWithLabels.png" />
    <Resource Include="Resources\BingCanvasDark.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\BingRoad.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\AzureTrafficLight.png" />
    <Resource Include="Resources\AzureTrafficRelative.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\AzureTrafficDelay.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\AzureTerraOverlay.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\AzureWeatherRadar.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\AzureLabelsDarkGrey.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\AzureHybridDarkGrey.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\AzureHybridRoad2.png" />
    <Resource Include="Resources\AzureLabelsRoad.png" />
    <Resource Include="Resources\AzureTrafficAbsolute.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\azure_traffic_relative_dark.png" />
  </ItemGroup>
</Project>