<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>IGDataGrid</RootNamespace>
    <AssemblyName>IGDataGrid</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Infragistics.WPF.ColorPicker.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.DataGrids.Excel.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.DataGrids.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.DataGrids.Word.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Documents.Core.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Editors.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Excel.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Slider.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Word.Trial" Version="25.1.117" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Controls\Images\contax.png" />
    <Resource Include="Controls\Images\email.png" />
    <Resource Include="Controls\Images\home.png" />
    <Resource Include="Controls\Images\mobile.png" />
    <Resource Include="Controls\Images\office.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="DataSources\MutualFundsList.xml" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\FieldChooserIcon.png" />
    <Resource Include="Resources\GroupByExternal.png" />
    <Resource Include="Resources\offline.png" />
    <Resource Include="Resources\online.png" />
    <Resource Include="Resources\SampleBallBlue.png" />
    <Resource Include="Resources\SampleBallOrange.png" />
  </ItemGroup>
</Project>