//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGPersistenceFramework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersistenceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public PersistenceStrings()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGPersistenceFramework.Resources.PersistenceStrings", typeof(PersistenceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string CPF_Button_Apply {
            get {
                return ResourceManager.GetString("CPF_Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log.
        /// </summary>
        public static string CPF_Button_Clear {
            get {
                return ResourceManager.GetString("CPF_Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Settings.
        /// </summary>
        public static string CPF_Button_Load {
            get {
                return ResourceManager.GetString("CPF_Button_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string CPF_Button_Save {
            get {
                return ResourceManager.GetString("CPF_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel &apos;Width&apos; Save.
        /// </summary>
        public static string CPF_Events_CheckboxText {
            get {
                return ResourceManager.GetString("CPF_Events_CheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events Log.
        /// </summary>
        public static string CPF_Events_PanelHeader {
            get {
                return ResourceManager.GetString("CPF_Events_PanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        public static string CPF_Group_Pref {
            get {
                return ResourceManager.GetString("CPF_Group_Pref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Channel 1.
        /// </summary>
        public static string CPF_Group_TVChannel1 {
            get {
                return ResourceManager.GetString("CPF_Group_TVChannel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Channel 2.
        /// </summary>
        public static string CPF_Group_TVChannel2 {
            get {
                return ResourceManager.GetString("CPF_Group_TVChannel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Channel 3.
        /// </summary>
        public static string CPF_Group_TVChannel3 {
            get {
                return ResourceManager.GetString("CPF_Group_TVChannel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Channel 4.
        /// </summary>
        public static string CPF_Group_TVChannel4 {
            get {
                return ResourceManager.GetString("CPF_Group_TVChannel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Channel 5.
        /// </summary>
        public static string CPF_Group_TVChannel5 {
            get {
                return ResourceManager.GetString("CPF_Group_TVChannel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Channel 6.
        /// </summary>
        public static string CPF_Group_TVChannel6 {
            get {
                return ResourceManager.GetString("CPF_Group_TVChannel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string CPF_Height {
            get {
                return ResourceManager.GetString("CPF_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Properties.
        /// </summary>
        public static string CPF_IgnoredSettings_IgnoredProp {
            get {
                return ResourceManager.GetString("CPF_IgnoredSettings_IgnoredProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string CPF_Left {
            get {
                return ResourceManager.GetString("CPF_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string CPF_PersistImageControl_Opacity {
            get {
                return ResourceManager.GetString("CPF_PersistImageControl_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Settings.
        /// </summary>
        public static string CPF_PersistImageControl_PanelHeader {
            get {
                return ResourceManager.GetString("CPF_PersistImageControl_PanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string CPF_PersistImageControl_Size {
            get {
                return ResourceManager.GetString("CPF_PersistImageControl_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string CPF_PersistXWGrid_DOB {
            get {
                return ResourceManager.GetString("CPF_PersistXWGrid_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string CPF_PersistXWGrid_FirstName {
            get {
                return ResourceManager.GetString("CPF_PersistXWGrid_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string CPF_PersistXWGrid_Gender {
            get {
                return ResourceManager.GetString("CPF_PersistXWGrid_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string CPF_PersistXWGrid_LastName {
            get {
                return ResourceManager.GetString("CPF_PersistXWGrid_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string CPF_Settings {
            get {
                return ResourceManager.GetString("CPF_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string CPF_Top {
            get {
                return ResourceManager.GetString("CPF_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string CPF_Width {
            get {
                return ResourceManager.GetString("CPF_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Window.
        /// </summary>
        public static string CPF_XWDW_Header_Base {
            get {
                return ResourceManager.GetString("CPF_XWDW_Header_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Window.
        /// </summary>
        public static string CPF_XWDW_Header_Target {
            get {
                return ResourceManager.GetString("CPF_XWDW_Header_Target", resourceCulture);
            }
        }
    }
}
