<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>IGSurfaceChart</RootNamespace>
    <AssemblyName>IGSurfaceChart</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\Output\</OutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Infragistics.WPF.ColorPicker.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.DataVisualization.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Documents.Core.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Editors.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Excel.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Slider.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.SurfaceChart3D.Trial" Version="25.1.117" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Assets\Infragistics.Samples.Assets.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\shapefiles\hawaii_big_island.dbf" />
    <Resource Include="Resources\shapefiles\hawaii_big_island.shp" />
    <Resource Include="Resources\shapefiles\world_countries.dbf" />
    <Resource Include="Resources\shapefiles\world_countries.shp" />
    <Resource Include="Resources\shapefiles\world_countries.shx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\shapefiles\hawaii_big_island.shx" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\ExcelFiles\SampleFinancialData.xlsx" />
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties DocumentXCommentEditorState="&lt;HtmlEditState&gt;&#xA;  &lt;Attributes /&gt;&#xA;&lt;/HtmlEditState&gt;" />
    </VisualStudio>
  </ProjectExtensions>
</Project>