//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGExtensions.Common.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeoStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public GeoStrings()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGExtensions.Common.Assets.Resources.GeoStrings", typeof(GeoStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berlin.
        /// </summary>
        public static string XWM_Location_Berlin {
            get {
                return ResourceManager.GetString("XWM_Location_Berlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delhi.
        /// </summary>
        public static string XWM_Location_Delhi {
            get {
                return ResourceManager.GetString("XWM_Location_Delhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to London.
        /// </summary>
        public static string XWM_Location_London {
            get {
                return ResourceManager.GetString("XWM_Location_London", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LosAngeles.
        /// </summary>
        public static string XWM_Location_LosAngeles {
            get {
                return ResourceManager.GetString("XWM_Location_LosAngeles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manila.
        /// </summary>
        public static string XWM_Location_Manila {
            get {
                return ResourceManager.GetString("XWM_Location_Manila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MexicoCity.
        /// </summary>
        public static string XWM_Location_MexicoCity {
            get {
                return ResourceManager.GetString("XWM_Location_MexicoCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moscow.
        /// </summary>
        public static string XWM_Location_Moscow {
            get {
                return ResourceManager.GetString("XWM_Location_Moscow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mumbai.
        /// </summary>
        public static string XWM_Location_Mumbai {
            get {
                return ResourceManager.GetString("XWM_Location_Mumbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewYork.
        /// </summary>
        public static string XWM_Location_NewYork {
            get {
                return ResourceManager.GetString("XWM_Location_NewYork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaoPaulo.
        /// </summary>
        public static string XWM_Location_SaoPaulo {
            get {
                return ResourceManager.GetString("XWM_Location_SaoPaulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sedney.
        /// </summary>
        public static string XWM_Location_Sedney {
            get {
                return ResourceManager.GetString("XWM_Location_Sedney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seoul.
        /// </summary>
        public static string XWM_Location_Seoul {
            get {
                return ResourceManager.GetString("XWM_Location_Seoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shanghai.
        /// </summary>
        public static string XWM_Location_Shanghai {
            get {
                return ResourceManager.GetString("XWM_Location_Shanghai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokyo.
        /// </summary>
        public static string XWM_Location_Tokyo {
            get {
                return ResourceManager.GetString("XWM_Location_Tokyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warsaw.
        /// </summary>
        public static string XWM_Location_Warsaw {
            get {
                return ResourceManager.GetString("XWM_Location_Warsaw", resourceCulture);
            }
        }
    }
}
