//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGExtensions.Common.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShareLinkStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ShareLinkStrings()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGExtensions.Common.Assets.Resources.ShareLinkStrings", typeof(ShareLinkStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Feed.
        /// </summary>
        public static string BlogFeed {
            get {
                return ResourceManager.GetString("BlogFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post To Blogger.
        /// </summary>
        public static string Blogger {
            get {
                return ResourceManager.GetString("Blogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Delicious.
        /// </summary>
        public static string Delicious {
            get {
                return ResourceManager.GetString("Delicious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share On Digg.
        /// </summary>
        public static string Digg {
            get {
                return ResourceManager.GetString("Digg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share On Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share On Friend Feed.
        /// </summary>
        public static string FriendFeed {
            get {
                return ResourceManager.GetString("FriendFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Bookmark.
        /// </summary>
        public static string GoogleBookmark {
            get {
                return ResourceManager.GetString("GoogleBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share On Google Plus.
        /// </summary>
        public static string GooglePlus {
            get {
                return ResourceManager.GetString("GooglePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share On LinkedIn.
        /// </summary>
        public static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share On MySpace.
        /// </summary>
        public static string MySpace {
            get {
                return ResourceManager.GetString("MySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin It.
        /// </summary>
        public static string PinIt {
            get {
                return ResourceManager.GetString("PinIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PDF And Print Friendly.
        /// </summary>
        public static string PrintFriendly {
            get {
                return ResourceManager.GetString("PrintFriendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share On Reddit.
        /// </summary>
        public static string Reddit {
            get {
                return ResourceManager.GetString("Reddit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share On StumbleUpon.
        /// </summary>
        public static string StumbleUpon {
            get {
                return ResourceManager.GetString("StumbleUpon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet This.
        /// </summary>
        public static string Tweet {
            get {
                return ResourceManager.GetString("Tweet", resourceCulture);
            }
        }
    }
}
