<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>IGPropertyGrid</RootNamespace>
    <AssemblyName>IGPropertyGrid</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>DEBUG;TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>DEBUG;TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Infragistics.WPF.Calendar.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.ColorPicker.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Controls.Editors.XamDateTimeInput.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Controls.Editors.XamMaskedInput.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.DataGrids.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Editors.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.PropertyGrid.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Slider.Trial" Version="25.1.117" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\left-arrow.png" />
    <Resource Include="Images\right-arrow.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\number1.png" />
    <Resource Include="Images\number2.png" />
  </ItemGroup>
</Project>