<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>IGRibbon</RootNamespace>
    <AssemblyName>IGRibbon</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Infragistics.WPF.Editors.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.Ribbon.Trial" Version="25.2.24" />
    <PackageReference Include="System.Runtime.Serialization.Formatters" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Bold.png" />
    <Resource Include="Images\CenterAlign.png" />
    <Resource Include="Images\Close_Large.png" />
    <Resource Include="Images\color_chooser_32x32.png" />
    <Resource Include="Images\EditCopy.png" />
    <Resource Include="Images\EditCut.png" />
    <Resource Include="Images\EditRedo.png" />
    <Resource Include="Images\EditUndo.png" />
    <Resource Include="Images\FontColor.png" />
    <Resource Include="Images\FontDlgs.png" />
    <Resource Include="Images\FormatPainter.png" />
    <Resource Include="Images\GalleryItem_50sGreen.png" />
    <Resource Include="Images\GalleryItem_BlatantlyBold.png" />
    <Resource Include="Images\GalleryItem_BoldlyBlue.png" />
    <Resource Include="Images\GalleryItem_ItalicizedIndigo.png" />
    <Resource Include="Images\GalleryItem_MediumRed.png" />
    <Resource Include="Images\GalleryItem_Normal.png" />
    <Resource Include="Images\GalleryItem_Pink.png" />
    <Resource Include="Images\GalleryItem_UnmistakablyLarge.png" />
    <Resource Include="Images\GalleryItem_Vivid.png" />
    <Resource Include="Images\Italic.png" />
    <Resource Include="Images\JustifyAlign.png" />
    <Resource Include="Images\LeftAlign.png" />
    <Resource Include="Images\New_Large.png" />
    <Resource Include="Images\Open_Large.png" />
    <Resource Include="Images\Paste_16x16.png" />
    <Resource Include="Images\Paste_32x32.png" />
    <Resource Include="Images\QuickStyles_16x16.png" />
    <Resource Include="Images\QuickStyles_32x32.png" />
    <Resource Include="Images\RightAlign.png" />
    <Resource Include="Images\Save_Large.png" />
    <Resource Include="Images\Theme_Black.png" />
    <Resource Include="Images\Theme_Blue.png" />
    <Resource Include="Images\Theme_IG.png" />
    <Resource Include="Images\Theme_Large.png" />
    <Resource Include="Images\Theme_Silver.png" />
    <Resource Include="Images\Underline.png" />
    <Resource Include="Images\Watermark.png" />
    <Resource Include="Images\WatermarkTool.png" />
    <Resource Include="Images\xamRibbonDefaultApplicationIcon.png" />
    <Resource Include="Images\xamRibbonWindow_Screenshot.ja.png" />
    <Resource Include="Images\xamRibbonWindow_Screenshot.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Theme_Metro.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Exit_16x16.png" />
    <Resource Include="Images\Open_16x16.png" />
    <Resource Include="Images\Options_16x16.png" />
    <Resource Include="Images\SaveAs_16x16.png" />
    <Resource Include="Images\Save_16x16.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Close_16x16.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Internet_32x32.png" />
    <Resource Include="Images\Intranet_32x32.png" />
    <Resource Include="Images\Local_32x32.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Theme_MetroDark.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\xamRibbonWindow.png" />
    <Resource Include="Images\xamRibbonWindowNoRibbon.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\help.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\CenterAlignLight.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\JustifyAlignLight.png" />
    <Resource Include="Images\LeftAlignLight.png" />
    <Resource Include="Images\RightAlignLight.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\BoldLight.png" />
    <Resource Include="Images\ItalicLight.png" />
    <Resource Include="Images\UnderlineLight.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Theme_RoyalDark.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Theme_RoyalLight.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\xamRibbonDefaultApplicationIconGray.png" />
  </ItemGroup>
</Project>