//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGRibbon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RibbonResourceStringsSample {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public RibbonResourceStringsSample() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGRibbon.Resources.RibbonResourceStringsSample", typeof(RibbonResourceStringsSample).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Add Gallery To Quick Access Toolbar.
        /// </summary>
        public static string AddGalleryToQAT {
            get {
                return ResourceManager.GetString("AddGalleryToQAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Add To Quick Access Toolbar.
        /// </summary>
        public static string AddToQAT {
            get {
                return ResourceManager.GetString("AddToQAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] File.
        /// </summary>
        public static string ApplicationMenuHeaderCaption {
            get {
                return ResourceManager.GetString("ApplicationMenuHeaderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Choose Commands From.
        /// </summary>
        public static string ChooseCommandsFromLabel {
            get {
                return ResourceManager.GetString("ChooseCommandsFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Collapse All.
        /// </summary>
        public static string CollapseAllLabel {
            get {
                return ResourceManager.GetString("CollapseAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Customize Quick Access Toolbar....
        /// </summary>
        public static string CustomizeQAT {
            get {
                return ResourceManager.GetString("CustomizeQAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Customize Quick Access Toolbar.
        /// </summary>
        public static string CustomizeQATCaption {
            get {
                return ResourceManager.GetString("CustomizeQATCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Quick Access Toolbar Settings.
        /// </summary>
        public static string CustomizeQATSettingsLabel {
            get {
                return ResourceManager.GetString("CustomizeQATSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Customize the Ribbon....
        /// </summary>
        public static string CustomizeRibbon {
            get {
                return ResourceManager.GetString("CustomizeRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Customize Ribbon Settings.
        /// </summary>
        public static string CustomizeRibbonSettingsLabel {
            get {
                return ResourceManager.GetString("CustomizeRibbonSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Customize the QAT Layout.
        /// </summary>
        public static string CustomizeTheQATLabel {
            get {
                return ResourceManager.GetString("CustomizeTheQATLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Customize the Ribbon Layout.
        /// </summary>
        public static string CustomizeTheRibbonLabel {
            get {
                return ResourceManager.GetString("CustomizeTheRibbonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Close.
        /// </summary>
        public static string DialogCancelButton {
            get {
                return ResourceManager.GetString("DialogCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Ribbon and QAT Customization.
        /// </summary>
        public static string DialogCaption {
            get {
                return ResourceManager.GetString("DialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Ok.
        /// </summary>
        public static string DialogOkButton {
            get {
                return ResourceManager.GetString("DialogOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Export All Customizations.
        /// </summary>
        public static string ExportAllCustomizations {
            get {
                return ResourceManager.GetString("ExportAllCustomizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Import All Customizations.
        /// </summary>
        public static string ImportAllCustomizations {
            get {
                return ResourceManager.GetString("ImportAllCustomizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Imp/Exp.
        /// </summary>
        public static string ImportExportDropdownLabel {
            get {
                return ResourceManager.GetString("ImportExportDropdownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] All Commands.
        /// </summary>
        public static string ItemType_AllCommands {
            get {
                return ResourceManager.GetString("ItemType_AllCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] All Tabs.
        /// </summary>
        public static string ItemType_AllTabs {
            get {
                return ResourceManager.GetString("ItemType_AllTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Application Menu.
        /// </summary>
        public static string ItemType_ApplicationMenuCommands {
            get {
                return ResourceManager.GetString("ItemType_ApplicationMenuCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] File Tab.
        /// </summary>
        public static string ItemType_ApplicationMenuCommands2010 {
            get {
                return ResourceManager.GetString("ItemType_ApplicationMenuCommands2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Contextual Tabs.
        /// </summary>
        public static string ItemType_ContextualTabs {
            get {
                return ResourceManager.GetString("ItemType_ContextualTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Main Tabs.
        /// </summary>
        public static string ItemType_MainTabs {
            get {
                return ResourceManager.GetString("ItemType_MainTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Popular Commands.
        /// </summary>
        public static string ItemType_PopularCommands {
            get {
                return ResourceManager.GetString("ItemType_PopularCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] QAT.
        /// </summary>
        public static string ItemType_QAT {
            get {
                return ResourceManager.GetString("ItemType_QAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Tools Not In Ribbon.
        /// </summary>
        public static string ItemType_ToolsNotInRibbon {
            get {
                return ResourceManager.GetString("ItemType_ToolsNotInRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] ActivationActionDelay cannot be less than zero..
        /// </summary>
        public static string LE_ActivationActionDelayLessThanZero {
            get {
                return ResourceManager.GetString("LE_ActivationActionDelayLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] ActivationInitialActionDelay cannot be less than zero..
        /// </summary>
        public static string LE_ActivationInitialActionDelayLessThanZero {
            get {
                return ResourceManager.GetString("LE_ActivationInitialActionDelayLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] A ButtonGroup can only be placed inside of a RibbonGroup..
        /// </summary>
        public static string LE_ButtonGroupOutsideOfGroupControl {
            get {
                return ResourceManager.GetString("LE_ButtonGroupOutsideOfGroupControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] A GalleryTool already exists in this Menu, only one GalleryTool per menu is allowed..
        /// </summary>
        public static string LE_GalleryToolAlreadyExistInMenu {
            get {
                return ResourceManager.GetString("LE_GalleryToolAlreadyExistInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] You cannot use a GalleryTool outside of a MenuTool..
        /// </summary>
        public static string LE_GalleryToolOutsideOfMenu {
            get {
                return ResourceManager.GetString("LE_GalleryToolOutsideOfMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Group with Id &apos;{0}&apos; already exists. Cannot add multiple group instances with the same Id..
        /// </summary>
        public static string LE_GroupRegisteredWithSameId {
            get {
                return ResourceManager.GetString("LE_GroupRegisteredWithSameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Object is not a Keytip.
        /// </summary>
        public static string LE_KeyTipArgumentException {
            get {
                return ResourceManager.GetString("LE_KeyTipArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Tool with Id &apos;{0}&apos; already exists. Cannot add multiple tool instances with the same Id..
        /// </summary>
        public static string LE_ToolRegisteredWithSameId {
            get {
                return ResourceManager.GetString("LE_ToolRegisteredWithSameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Minimize the Ribbon.
        /// </summary>
        public static string MinimizeRibbon {
            get {
                return ResourceManager.GetString("MinimizeRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Minimize the Ribbon.
        /// </summary>
        public static string MinimizeRibbonToolCaption {
            get {
                return ResourceManager.GetString("MinimizeRibbonToolCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] More Commands....
        /// </summary>
        public static string MoreCommandsToolCaption {
            get {
                return ResourceManager.GetString("MoreCommandsToolCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] + New Tab.
        /// </summary>
        public static string NewTabLabel {
            get {
                return ResourceManager.GetString("NewTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] New Group (Custom).
        /// </summary>
        public static string Node_CreateNewGroup {
            get {
                return ResourceManager.GetString("Node_CreateNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Create New Group.
        /// </summary>
        public static string Node_CreateNewGroupPlaceHolder {
            get {
                return ResourceManager.GetString("Node_CreateNewGroupPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] New Tab (Custom).
        /// </summary>
        public static string Node_CreateNewTab {
            get {
                return ResourceManager.GetString("Node_CreateNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Main Tabs.
        /// </summary>
        public static string Node_MainTabs {
            get {
                return ResourceManager.GetString("Node_MainTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Quick Access Toolbar.
        /// </summary>
        public static string QATCustomizationTab {
            get {
                return ResourceManager.GetString("QATCustomizationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Show the QAT below the Ribbon.
        /// </summary>
        public static string QATPositionLabel {
            get {
                return ResourceManager.GetString("QATPositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Remove From Quick Access Toolbar.
        /// </summary>
        public static string RemoveFromQAT {
            get {
                return ResourceManager.GetString("RemoveFromQAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] All Customizations.
        /// </summary>
        public static string ResetAllCustomizations {
            get {
                return ResourceManager.GetString("ResetAllCustomizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Reset.
        /// </summary>
        public static string ResetDropdownLabel {
            get {
                return ResourceManager.GetString("ResetDropdownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Reset to original.
        /// </summary>
        public static string ResetLayoutLabel {
            get {
                return ResourceManager.GetString("ResetLayoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] QAT (Non-Ribbon) Customizations.
        /// </summary>
        public static string ResetQATCustomizationsOnlyLabel {
            get {
                return ResourceManager.GetString("ResetQATCustomizationsOnlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Ribbbon (Non-Qat) Customizations.
        /// </summary>
        public static string ResetRibbonCustomizationsOnlyLabel {
            get {
                return ResourceManager.GetString("ResetRibbonCustomizationsOnlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Customize Ribbon.
        /// </summary>
        public static string RibbonCustomizationTab {
            get {
                return ResourceManager.GetString("RibbonCustomizationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Share or save.
        /// </summary>
        public static string SaveOrShareLabel {
            get {
                return ResourceManager.GetString("SaveOrShareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] add.
        /// </summary>
        public static string ShiftRightButton {
            get {
                return ResourceManager.GetString("ShiftRightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Show Above the Ribbon.
        /// </summary>
        public static string ShowAboveToolCaption {
            get {
                return ResourceManager.GetString("ShowAboveToolCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Show Below the Ribbon.
        /// </summary>
        public static string ShowBelowToolCaption {
            get {
                return ResourceManager.GetString("ShowBelowToolCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Show Quick Access Toolbar Above the Ribbon.
        /// </summary>
        public static string ShowQATAbove {
            get {
                return ResourceManager.GetString("ShowQATAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Show Quick Access Toolbar Below the Ribbon.
        /// </summary>
        public static string ShowQATBelow {
            get {
                return ResourceManager.GetString("ShowQATBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Button Group.
        /// </summary>
        public static string ToolDesc_ButtonGroup {
            get {
                return ResourceManager.GetString("ToolDesc_ButtonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Horizontal Tool Container.
        /// </summary>
        public static string ToolDesc_HorizContainer {
            get {
                return ResourceManager.GetString("ToolDesc_HorizContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Localized] Vertical Tool Container.
        /// </summary>
        public static string ToolDesc_VertContainer {
            get {
                return ResourceManager.GetString("ToolDesc_VertContainer", resourceCulture);
            }
        }
    }
}
