//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGExtensions.Common.Maps.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImageryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ImageryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGExtensions.Common.Maps.Assets.Resources.ImageryStrings", typeof(ImageryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Map Hybrid Imagery.
        /// </summary>
        public static string Imagery_BingMapHybrid {
            get {
                return ResourceManager.GetString("Imagery_BingMapHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Map Satellite Imagery.
        /// </summary>
        public static string Imagery_BingMapSatellite {
            get {
                return ResourceManager.GetString("Imagery_BingMapSatellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Map Street Imagery.
        /// </summary>
        public static string Imagery_BingMapStreet {
            get {
                return ResourceManager.GetString("Imagery_BingMapStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Quest Satellite Imagery.
        /// </summary>
        public static string Imagery_MapQuestSatellite {
            get {
                return ResourceManager.GetString("Imagery_MapQuestSatellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Quest Street Imagery.
        /// </summary>
        public static string Imagery_MapQuestStreet {
            get {
                return ResourceManager.GetString("Imagery_MapQuestStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Street Map Imagery.
        /// </summary>
        public static string Imagery_OpenStreetMap {
            get {
                return ResourceManager.GetString("Imagery_OpenStreetMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Map Tiles.
        /// </summary>
        public static string Tiles_BingMap {
            get {
                return ResourceManager.GetString("Tiles_BingMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESRI USA Overlay Tiles.
        /// </summary>
        public static string Tiles_ESRI_USA_Overlay {
            get {
                return ResourceManager.GetString("Tiles_ESRI_USA_Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESRI World Map Tiles.
        /// </summary>
        public static string Tiles_ESRI_World_Map {
            get {
                return ResourceManager.GetString("Tiles_ESRI_World_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESRI World Overlay Tiles.
        /// </summary>
        public static string Tiles_ESRI_World_Overlay {
            get {
                return ResourceManager.GetString("Tiles_ESRI_World_Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Quest Tiles.
        /// </summary>
        public static string Tiles_MapQuest {
            get {
                return ResourceManager.GetString("Tiles_MapQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Street Map Tiles.
        /// </summary>
        public static string Tiles_OpenStreetMap {
            get {
                return ResourceManager.GetString("Tiles_OpenStreetMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Average Household Size Overlay.
        /// </summary>
        public static string UsaAverageHouseholdSizeOverlay {
            get {
                return ResourceManager.GetString("UsaAverageHouseholdSizeOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides the average household size in the United States in 2010. Dark green shows the areas with the highest average size, dark purple the lowest average size..
        /// </summary>
        public static string UsaAverageHouseholdSizeOverlayInfo {
            get {
                return ResourceManager.GetString("UsaAverageHouseholdSizeOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Diversity Index Overlay.
        /// </summary>
        public static string UsaDiversityIndexOverlay {
            get {
                return ResourceManager.GetString("UsaDiversityIndexOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides racial and ethnic diversity in the United States..
        /// </summary>
        public static string UsaDiversityIndexOverlayInfo {
            get {
                return ResourceManager.GetString("UsaDiversityIndexOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Labor Force Participation Overlay.
        /// </summary>
        public static string UsaLaborForceParticipationOverlay {
            get {
                return ResourceManager.GetString("UsaLaborForceParticipationOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides the rates of labor force participation of people at working age in the United States in 2010.
        /// </summary>
        public static string UsaLaborForceParticipationOverlayInfo {
            get {
                return ResourceManager.GetString("UsaLaborForceParticipationOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Median Age Overlay.
        /// </summary>
        public static string UsaMedianAgeOverlay {
            get {
                return ResourceManager.GetString("UsaMedianAgeOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides the median age of people in the United States in 2010..
        /// </summary>
        public static string UsaMedianAgeOverlayInfo {
            get {
                return ResourceManager.GetString("UsaMedianAgeOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Median Home Value Overlay.
        /// </summary>
        public static string UsaMedianHomeValueOverlay {
            get {
                return ResourceManager.GetString("UsaMedianHomeValueOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides the median home value in the United States in 2010..
        /// </summary>
        public static string UsaMedianHomeValueOverlayInfo {
            get {
                return ResourceManager.GetString("UsaMedianHomeValueOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Median Household Income Overlay.
        /// </summary>
        public static string UsaMedianHouseholdIncomeOverlay {
            get {
                return ResourceManager.GetString("UsaMedianHouseholdIncomeOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides the median household income in the United States in 2010..
        /// </summary>
        public static string UsaMedianHouseholdIncomeOverlayInfo {
            get {
                return ResourceManager.GetString("UsaMedianHouseholdIncomeOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Median Net Worth Overlay.
        /// </summary>
        public static string UsaMedianNetWorthOverlay {
            get {
                return ResourceManager.GetString("UsaMedianNetWorthOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides the median household net worth in the United States in 2010..
        /// </summary>
        public static string UsaMedianNetWorthOverlayInfo {
            get {
                return ResourceManager.GetString("UsaMedianNetWorthOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Owner Occupied Housing.
        /// </summary>
        public static string UsaOwnerOccupiedHousingOverlay {
            get {
                return ResourceManager.GetString("UsaOwnerOccupiedHousingOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI overlay map provides the rates of owner occupied housing in the United States in 2010..
        /// </summary>
        public static string UsaOwnerOccupiedHousingOverlayInfo {
            get {
                return ResourceManager.GetString("UsaOwnerOccupiedHousingOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Population By Gender Overlay.
        /// </summary>
        public static string UsaPopulationByGenderOverlay {
            get {
                return ResourceManager.GetString("UsaPopulationByGenderOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides the relative percentage of males and females in the United States in 2010. Blue areas on the map have relatively more males. Pink areas have relatively more females..
        /// </summary>
        public static string UsaPopulationByGenderOverlayInfo {
            get {
                return ResourceManager.GetString("UsaPopulationByGenderOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Population Change 1990-2000 Overlay.
        /// </summary>
        public static string UsaPopulationChange2000Overlay {
            get {
                return ResourceManager.GetString("UsaPopulationChange2000Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides the annual compound rate of total population change in the United States from 1990 to 2000.
        /// </summary>
        public static string UsaPopulationChange2000OverlayInfo {
            get {
                return ResourceManager.GetString("UsaPopulationChange2000OverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Population Change 2000-2010 Overlay.
        /// </summary>
        public static string UsaPopulationChange2010Overlay {
            get {
                return ResourceManager.GetString("UsaPopulationChange2010Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides the annual compound rate of total population change in the United States from 2000 to 2010.
        /// </summary>
        public static string UsaPopulationChange2010OverlayInfo {
            get {
                return ResourceManager.GetString("UsaPopulationChange2010OverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Population Density Overlay.
        /// </summary>
        public static string UsaPopulationDensityOverlay {
            get {
                return ResourceManager.GetString("UsaPopulationDensityOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides the population density in the United States in 2010..
        /// </summary>
        public static string UsaPopulationDensityOverlayInfo {
            get {
                return ResourceManager.GetString("UsaPopulationDensityOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Projected Population Growth 2015 Overlay.
        /// </summary>
        public static string UsaPopulationGrowth2015Overlay {
            get {
                return ResourceManager.GetString("UsaPopulationGrowth2015Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides the projected annual compound population growth rate in the United States from 2010 to 2015.
        /// </summary>
        public static string UsaPopulationGrowth2015OverlayInfo {
            get {
                return ResourceManager.GetString("UsaPopulationGrowth2015OverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Population Older than Age 64 Overlay.
        /// </summary>
        public static string UsaPopulationOlderThanAge64Overlay {
            get {
                return ResourceManager.GetString("UsaPopulationOlderThanAge64Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI overlay map provides the percentage of the population older than 64 years of age in the United States in 2010..
        /// </summary>
        public static string UsaPopulationOlderThanAge64OverlayInfo {
            get {
                return ResourceManager.GetString("UsaPopulationOlderThanAge64OverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Population Younger than Age 18 Overlay.
        /// </summary>
        public static string UsaPopulationYoungerThan18Overlay {
            get {
                return ResourceManager.GetString("UsaPopulationYoungerThan18Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI overlay map provides the percentage of the population younger than age 18 in the United States in 2010..
        /// </summary>
        public static string UsaPopulationYoungerThan18OverlayInfo {
            get {
                return ResourceManager.GetString("UsaPopulationYoungerThan18OverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Rail Network Overlay.
        /// </summary>
        public static string UsaRailNetworkOverlay {
            get {
                return ResourceManager.GetString("UsaRailNetworkOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI overlay map provides railway system in the United States. The data set, from the Federal Railroad Administration (FRA) rail network database, provides location and attribute information for use in national and regional network analysis applications..
        /// </summary>
        public static string UsaRailNetworkOverlayInfo {
            get {
                return ResourceManager.GetString("UsaRailNetworkOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Retail Spending Potential Overlay.
        /// </summary>
        public static string UsaRetailSpendingPotentialOverlay {
            get {
                return ResourceManager.GetString("UsaRetailSpendingPotentialOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides the Spending Potential Index (SPI) for retail goods in the United States in 2010.
        /// </summary>
        public static string UsaRetailSpendingPotentialOverlayInfo {
            get {
                return ResourceManager.GetString("UsaRetailSpendingPotentialOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Social Vulnerability Overlay.
        /// </summary>
        public static string UsaSocialVulnerabilityOverlay {
            get {
                return ResourceManager.GetString("UsaSocialVulnerabilityOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides a simple summary of the social vulnerability of populations in each state or county in the United States in 2009.
        /// </summary>
        public static string UsaSocialVulnerabilityOverlayInfo {
            get {
                return ResourceManager.GetString("UsaSocialVulnerabilityOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Soil Survey Overlay.
        /// </summary>
        public static string UsaSoilSurveyOverlay {
            get {
                return ResourceManager.GetString("UsaSoilSurveyOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI overlay map provides the Soil Survey Geographic (SSURGO) by the United States Department of Agriculture’s Natural Resources Conservation Service..
        /// </summary>
        public static string UsaSoilSurveyOverlayInfo {
            get {
                return ResourceManager.GetString("UsaSoilSurveyOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Unemployment Rate Overlay.
        /// </summary>
        public static string UsaUnemploymentRateOverlay {
            get {
                return ResourceManager.GetString("UsaUnemploymentRateOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI thematic map provides the unemployment rates in the United States in 2010.
        /// </summary>
        public static string UsaUnemploymentRateOverlayInfo {
            get {
                return ResourceManager.GetString("UsaUnemploymentRateOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Administrative Overlay.
        /// </summary>
        public static string WorldAdministrativeOverlay {
            get {
                return ResourceManager.GetString("WorldAdministrativeOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI overlay map provides administrative boundaries, cities, water features, physiographic features, parks, landmarks, highways, roads, railways, airports..
        /// </summary>
        public static string WorldAdministrativeOverlayInfo {
            get {
                return ResourceManager.GetString("WorldAdministrativeOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Boundaries Dark Overlay.
        /// </summary>
        public static string WorldBoundariesDarkOverlay {
            get {
                return ResourceManager.GetString("WorldBoundariesDarkOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI overlay map provides country, state, province, and county or equivalent boundaries and names of place for the World. It appears best when overlaying on dark basemaps.
        /// </summary>
        public static string WorldBoundariesDarkOverlayInfo {
            get {
                return ResourceManager.GetString("WorldBoundariesDarkOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Boundaries Light Overlay.
        /// </summary>
        public static string WorldBoundariesLightOverlay {
            get {
                return ResourceManager.GetString("WorldBoundariesLightOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI overlay map provides country, state, province, county or equivalent boundaries and names of place for the World. It appears best when overlaying on light basemaps..
        /// </summary>
        public static string WorldBoundariesLightOverlayInfo {
            get {
                return ResourceManager.GetString("WorldBoundariesLightOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World DeLorme’s Map.
        /// </summary>
        public static string WorldDeLormesMap {
            get {
                return ResourceManager.GetString("WorldDeLormesMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI basemap provides a DeLorme’s topographic map with seamless global data set that portrays transportation, hydrography, jurisdiction boundaries, and major geographic features..
        /// </summary>
        public static string WorldDeLormesMapInfo {
            get {
                return ResourceManager.GetString("WorldDeLormesMapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Imagery Map.
        /// </summary>
        public static string WorldImageryMap {
            get {
                return ResourceManager.GetString("WorldImageryMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI basemap provides satellite imagery for the World and high resolution imagery for the United States and other areas around the World..
        /// </summary>
        public static string WorldImageryMapInfo {
            get {
                return ResourceManager.GetString("WorldImageryMapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World LightGray Map.
        /// </summary>
        public static string WorldLightGrayMap {
            get {
                return ResourceManager.GetString("WorldLightGrayMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI basemap draws attention to your thematic content by providing a neutral background with minimal colors, labels, and features. .
        /// </summary>
        public static string WorldLightGrayMapInfo {
            get {
                return ResourceManager.GetString("WorldLightGrayMapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Light Gray Overlay.
        /// </summary>
        public static string WorldLightGrayOverlay {
            get {
                return ResourceManager.GetString("WorldLightGrayOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI overlay map provides labels for selected cities and towns around the World, in support of the WorldLight Gray basemap..
        /// </summary>
        public static string WorldLightGrayOverlayInfo {
            get {
                return ResourceManager.GetString("WorldLightGrayOverlayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World National Geographic Map.
        /// </summary>
        public static string WorldNationalGeographicMap {
            get {
                return ResourceManager.GetString("WorldNationalGeographicMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI basemap provides a general reference map for informational and educational purposes as well as a basemap by GIS professionals and other users for creating web maps and web mapping applications..
        /// </summary>
        public static string WorldNationalGeographicMapInfo {
            get {
                return ResourceManager.GetString("WorldNationalGeographicMapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Oceans Map.
        /// </summary>
        public static string WorldOceansMap {
            get {
                return ResourceManager.GetString("WorldOceansMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI basemap provides bathymetry, surface and subsurface feature names, and derived depths. This map layer is designed to be used as a basemap by marine GIS professionals and as a reference map by anyone interested in ocean data..
        /// </summary>
        public static string WorldOceansMapInfo {
            get {
                return ResourceManager.GetString("WorldOceansMapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Physical Map.
        /// </summary>
        public static string WorldPhysicalMap {
            get {
                return ResourceManager.GetString("WorldPhysicalMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI basemap provides the Natural Earth physical map for the World..
        /// </summary>
        public static string WorldPhysicalMapInfo {
            get {
                return ResourceManager.GetString("WorldPhysicalMapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Shaded Relief Map.
        /// </summary>
        public static string WorldShadedReliefMap {
            get {
                return ResourceManager.GetString("WorldShadedReliefMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI basemap provides surface elevation as shaded relief. It is intended for use as a basemap layer to add shaded relief to other GIS maps. .
        /// </summary>
        public static string WorldShadedReliefMapInfo {
            get {
                return ResourceManager.GetString("WorldShadedReliefMapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Street Map.
        /// </summary>
        public static string WorldStreetMap {
            get {
                return ResourceManager.GetString("WorldStreetMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI basemap provides highway level data for the World and street level data for North America, Europe, Southern Africa, parts of Asia, and more..
        /// </summary>
        public static string WorldStreetMapInfo {
            get {
                return ResourceManager.GetString("WorldStreetMapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Terrain Map.
        /// </summary>
        public static string WorldTerrainMap {
            get {
                return ResourceManager.GetString("WorldTerrainMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI basemap provides shaded relief imagery, bathymetry, and coastal water features designed to provide a neutral background for other data layers..
        /// </summary>
        public static string WorldTerrainMapInfo {
            get {
                return ResourceManager.GetString("WorldTerrainMapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Topographic Map.
        /// </summary>
        public static string WorldTopographicMap {
            get {
                return ResourceManager.GetString("WorldTopographicMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI basemap is a World topographic map with boundaries, cities, water features, physiographic features, parks, landmarks, transportation, and buildings..
        /// </summary>
        public static string WorldTopographicMapInfo {
            get {
                return ResourceManager.GetString("WorldTopographicMapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Transportation Overlay.
        /// </summary>
        public static string WorldTransportationOverlay {
            get {
                return ResourceManager.GetString("WorldTransportationOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ESRI overlay map provides a transportation and street name labels reference overlay that is particularly useful on top of imagery..
        /// </summary>
        public static string WorldTransportationOverlayInfo {
            get {
                return ResourceManager.GetString("WorldTransportationOverlayInfo", resourceCulture);
            }
        }
    }
}
