//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGBarcode.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BarcodeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public BarcodeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGBarcode.Resources.BarcodeStrings", typeof(BarcodeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the EciHeaderDisplayMode property to Show, so the EciNumber is encoded in the QrCode bits..
        /// </summary>
        public static string XB_EciHeaderDisplayMode_Note {
            get {
                return ResourceManager.GetString("XB_EciHeaderDisplayMode_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodes alphanumeric characters..
        /// </summary>
        public static string XWB_Alphanumeric {
            get {
                return ResourceManager.GetString("XWB_Alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Application Indicator is used only with Fnc1Mode=Industry. The valid values are {a-z, A-Z, 00-99}..
        /// </summary>
        public static string XWB_ApplicationIndicator {
            get {
                return ResourceManager.GetString("XWB_ApplicationIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Data.
        /// </summary>
        public static string XWB_ApplyData {
            get {
                return ResourceManager.GetString("XWB_ApplyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Data.
        /// </summary>
        public static string XWB_BarcodeData {
            get {
                return ResourceManager.GetString("XWB_BarcodeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE:.
        /// </summary>
        public static string XWB_BarcodeType {
            get {
                return ResourceManager.GetString("XWB_BarcodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bars Fill Mode.
        /// </summary>
        public static string XWB_BarsFillMode {
            get {
                return ResourceManager.GetString("XWB_BarsFillMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string XWB_ButtonClear {
            get {
                return ResourceManager.GetString("XWB_ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodes the data as bytes..
        /// </summary>
        public static string XWB_Byte {
            get {
                return ResourceManager.GetString("XWB_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code128Barcode.
        /// </summary>
        public static string XWB_Code128Barcode {
            get {
                return ResourceManager.GetString("XWB_Code128Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * The Code 128 UCC barcode symbology encodes a valid AI number. In the sample it starts with an application identifier (01) which is followed by 14 digits - code of the movie, start of the show, date of the show, row, column and discount code (two digits for each)..
        /// </summary>
        public static string XWB_Code128Ucc {
            get {
                return ResourceManager.GetString("XWB_Code128Ucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code39Barcode.
        /// </summary>
        public static string XWB_Code39Barcode {
            get {
                return ResourceManager.GetString("XWB_Code39Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code (modes 2 and 3).
        /// </summary>
        public static string XWB_CountryCode {
            get {
                return ResourceManager.GetString("XWB_CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        public static string XWB_Data {
            get {
                return ResourceManager.GetString("XWB_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string XWB_Dimensions {
            get {
                return ResourceManager.GetString("XWB_Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Note that the XDimension property is used with Stretch=&quot;None&quot;..
        /// </summary>
        public static string XWB_DimensionsNote {
            get {
                return ResourceManager.GetString("XWB_DimensionsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EanUpcBarcode.
        /// </summary>
        public static string XWB_EanUpcBarcode {
            get {
                return ResourceManager.GetString("XWB_EanUpcBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ECI.
        /// </summary>
        public static string XWB_Eci {
            get {
                return ResourceManager.GetString("XWB_Eci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Correction.
        /// </summary>
        public static string XWB_ErrorCorrection {
            get {
                return ResourceManager.GetString("XWB_ErrorCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCorrectionLevel:.
        /// </summary>
        public static string XWB_ErrorCorrectionLevel {
            get {
                return ResourceManager.GetString("XWB_ErrorCorrectionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is invalid because Code 39 only accepts 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-.$/+%. The assigned data contains lower case characters..
        /// </summary>
        public static string XWB_ErrorMessage {
            get {
                return ResourceManager.GetString("XWB_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string XWB_ExportToImage_Export {
            get {
                return ResourceManager.GetString("XWB_ExportToImage_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Options.
        /// </summary>
        public static string XWB_ExportToImage_Export_Options {
            get {
                return ResourceManager.GetString("XWB_ExportToImage_Export_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Format.
        /// </summary>
        public static string XWB_ExportToImage_File_Format {
            get {
                return ResourceManager.GetString("XWB_ExportToImage_File_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jpeg Quality.
        /// </summary>
        public static string XWB_ExportToImage_Jpeg_Quality {
            get {
                return ResourceManager.GetString("XWB_ExportToImage_Jpeg_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended.
        /// </summary>
        public static string XWB_Extended {
            get {
                return ResourceManager.GetString("XWB_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate checksum.
        /// </summary>
        public static string XWB_GenerateChecksum {
            get {
                return ResourceManager.GetString("XWB_GenerateChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gs1DataBarBarcode.
        /// </summary>
        public static string XWB_Gs1DataBarBarcode {
            get {
                return ResourceManager.GetString("XWB_Gs1DataBarBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interleaved2Of5Barcode.
        /// </summary>
        public static string XWB_Interleaved2Of5Barcode {
            get {
                return ResourceManager.GetString("XWB_Interleaved2Of5Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        public static string XWB_InvalidData {
            get {
                return ResourceManager.GetString("XWB_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodes Kanji characters..
        /// </summary>
        public static string XWB_Kanji {
            get {
                return ResourceManager.GetString("XWB_Kanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.infragistics.com/products/silverlight/barcode.
        /// </summary>
        public static string XWB_Link {
            get {
                return ResourceManager.GetString("XWB_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string XWB_Mode {
            get {
                return ResourceManager.GetString("XWB_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodes digits..
        /// </summary>
        public static string XWB_Numeric {
            get {
                return ResourceManager.GetString("XWB_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code (modes 2 and 3).
        /// </summary>
        public static string XWB_PostalCode {
            get {
                return ResourceManager.GetString("XWB_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string XWB_Print {
            get {
                return ResourceManager.GetString("XWB_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Changed:.
        /// </summary>
        public static string XWB_PropChanged {
            get {
                return ResourceManager.GetString("XWB_PropChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties Changed.
        /// </summary>
        public static string XWB_PropertyChanged {
            get {
                return ResourceManager.GetString("XWB_PropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code:.
        /// </summary>
        public static string XWB_QRCode {
            get {
                return ResourceManager.GetString("XWB_QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raised Events.
        /// </summary>
        public static string XWB_RaisedEvents {
            get {
                return ResourceManager.GetString("XWB_RaisedEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoyalMailBarcode.
        /// </summary>
        public static string XWB_RoyalMailBarcode {
            get {
                return ResourceManager.GetString("XWB_RoyalMailBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Data:.
        /// </summary>
        public static string XWB_SampleData {
            get {
                return ResourceManager.GetString("XWB_SampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string XWB_Save {
            get {
                return ResourceManager.GetString("XWB_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITED STATES POSTAL SERVICE.
        /// </summary>
        public static string XWB_SenderLine1 {
            get {
                return ResourceManager.GetString("XWB_SenderLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5501 ANYWHERE HWY.
        /// </summary>
        public static string XWB_SenderLine2 {
            get {
                return ResourceManager.GetString("XWB_SenderLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERRIFIELD VA 22082-8412.
        /// </summary>
        public static string XWB_SenderLine3 {
            get {
                return ResourceManager.GetString("XWB_SenderLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string XWB_Settings {
            get {
                return ResourceManager.GetString("XWB_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Barcode Text.
        /// </summary>
        public static string XWB_Show_Hide_Barcode_Text {
            get {
                return ResourceManager.GetString("XWB_Show_Hide_Barcode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretches.
        /// </summary>
        public static string XWB_Stretches {
            get {
                return ResourceManager.GetString("XWB_Stretches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbology Types.
        /// </summary>
        public static string XWB_Symbology_Types {
            get {
                return ResourceManager.GetString("XWB_Symbology_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol type:.
        /// </summary>
        public static string XWB_SymbolType {
            get {
                return ResourceManager.GetString("XWB_SymbolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default encoding mode - the most efficient..
        /// </summary>
        public static string XWB_Undefined {
            get {
                return ResourceManager.GetString("XWB_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Invalid Data.
        /// </summary>
        public static string XWB_Use_Invalid_Data {
            get {
                return ResourceManager.GetString("XWB_Use_Invalid_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Minimum Error Correction Level.
        /// </summary>
        public static string XWB_UseMinECL {
            get {
                return ResourceManager.GetString("XWB_UseMinECL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Data.
        /// </summary>
        public static string XWB_ValidData {
            get {
                return ResourceManager.GetString("XWB_ValidData", resourceCulture);
            }
        }
    }
}
