//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGPivotGrid.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SamplePivotGridStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SamplePivotGridStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGPivotGrid.Resources.SamplePivotGridStrings", typeof(SamplePivotGridStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string CellTotal {
            get {
                return ResourceManager.GetString("CellTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string ColumnsAreaBackgroundText {
            get {
                return ResourceManager.GetString("ColumnsAreaBackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a cube to begin.
        /// </summary>
        public static string CubesDropDownInitialText {
            get {
                return ResourceManager.GetString("CubesDropDownInitialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select database.
        /// </summary>
        public static string DatabasesDropDownInitialText {
            get {
                return ResourceManager.GetString("DatabasesDropDownInitialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defer Update.
        /// </summary>
        public static string DeferredUpdateLayoutCheckBoxLabel {
            get {
                return ResourceManager.GetString("DeferredUpdateLayoutCheckBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string DimensionsAreaBackgroundText {
            get {
                return ResourceManager.GetString("DimensionsAreaBackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Column Fields Here.
        /// </summary>
        public static string EmptyColumnsAreaText {
            get {
                return ResourceManager.GetString("EmptyColumnsAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Filter Fields Here.
        /// </summary>
        public static string EmptyFiltersAreaText {
            get {
                return ResourceManager.GetString("EmptyFiltersAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Data Items Here.
        /// </summary>
        public static string EmptyMeasuresAreaText {
            get {
                return ResourceManager.GetString("EmptyMeasuresAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Row Fields Here.
        /// </summary>
        public static string EmptyRowsAreaText {
            get {
                return ResourceManager.GetString("EmptyRowsAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string FiltersAreaBackgroundText {
            get {
                return ResourceManager.GetString("FiltersAreaBackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FilterTreeCancelButtonText {
            get {
                return ResourceManager.GetString("FilterTreeCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string FilterTreeOkButtonText {
            get {
                return ResourceManager.GetString("FilterTreeOkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find the cell in given indexies..
        /// </summary>
        public static string GetCell_CannotFindCell {
            get {
                return ResourceManager.GetString("GetCell_CannotFindCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count of visual tuples is not equals to count of visual indexes..
        /// </summary>
        public static string InvalidIndexiesCount {
            get {
                return ResourceManager.GetString("InvalidIndexiesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string MeasureFilterAddButtonText {
            get {
                return ResourceManager.GetString("MeasureFilterAddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string MeasureFilterAllText {
            get {
                return ResourceManager.GetString("MeasureFilterAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any of the following.
        /// </summary>
        public static string MeasureFilterAnyText {
            get {
                return ResourceManager.GetString("MeasureFilterAnyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string MeasureFilterClearAllButtonText {
            get {
                return ResourceManager.GetString("MeasureFilterClearAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching....
        /// </summary>
        public static string MeasureFilterDropdownMatchingText {
            get {
                return ResourceManager.GetString("MeasureFilterDropdownMatchingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure:.
        /// </summary>
        public static string MeasureFilterText {
            get {
                return ResourceManager.GetString("MeasureFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select measure group.
        /// </summary>
        public static string MeasureGroupsDropDownInitialText {
            get {
                return ResourceManager.GetString("MeasureGroupsDropDownInitialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures.
        /// </summary>
        public static string MeasuresAreaBackgroundText {
            get {
                return ResourceManager.GetString("MeasuresAreaBackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag fields between areas below:.
        /// </summary>
        public static string PanelCollectionsAreaLabel {
            get {
                return ResourceManager.GetString("PanelCollectionsAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column being physically resized is required to be in the resize columns collection..
        /// </summary>
        public static string ResizingColumnCannotBeRemovedException {
            get {
                return ResourceManager.GetString("ResizingColumnCannotBeRemovedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string RowsAreaBackgroundText {
            get {
                return ResourceManager.GetString("RowsAreaBackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows Groups.
        /// </summary>
        public static string RowsGroupsAreaBackgroundText {
            get {
                return ResourceManager.GetString("RowsGroupsAreaBackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown cell type: {0}..
        /// </summary>
        public static string UnknownCellType {
            get {
                return ResourceManager.GetString("UnknownCellType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Layout.
        /// </summary>
        public static string UpdateLayoutButtonText {
            get {
                return ResourceManager.GetString("UpdateLayoutButtonText", resourceCulture);
            }
        }
    }
}
