<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>IGBarcodeReader</RootNamespace>
    <AssemblyName>IGBarcodeReader</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
    <PackageReference Include="Infragistics.WPF.BarcodeReader.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Barcodes.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.DataVisualization.Trial" Version="25.1.117" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\2D.png" />
    <Resource Include="Images\EanUpc.png" />
    <Resource Include="Images\Gs1.png" />
    <Resource Include="Images\Linear.png" />
    <Resource Include="Images\QRCode.jpg" />
  </ItemGroup>
</Project>