//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGTileManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TileManagerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public TileManagerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGTileManager.Resources.TileManagerStrings", typeof(TileManagerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Tile.
        /// </summary>
        public static string LayoutAndBehavior_AddTilesToXamTilesControl_ConfigArea_AddButton {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_AddTilesToXamTilesControl_ConfigArea_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string LayoutAndBehavior_AddTilesToXamTilesControl_ConfigArea_Header {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_AddTilesToXamTilesControl_ConfigArea_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all Tiles.
        /// </summary>
        public static string LayoutAndBehavior_AddTilesToXamTilesControl_ConfigArea_RemoveButton {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_AddTilesToXamTilesControl_ConfigArea_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 2.
        /// </summary>
        public static string LayoutAndBehavior_AddTilesToXamTilesControl_ImageTile_Header {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_AddTilesToXamTilesControl_ImageTile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        public static string LayoutAndBehavior_AddTilesToXamTilesControl_NewlyAddedTile_Header {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_AddTilesToXamTilesControl_NewlyAddedTile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 1.
        /// </summary>
        public static string LayoutAndBehavior_AddTilesToXamTilesControl_Tile_Header {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_AddTilesToXamTilesControl_Tile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string LayoutAndBehavior_ChangeTileStates_ConfigArea_Header {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_ChangeTileStates_ConfigArea_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the Maximized State of Tile 1.
        /// </summary>
        public static string LayoutAndBehavior_ChangeTileStates_ConfigArea_MaximizeButton {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_ChangeTileStates_ConfigArea_MaximizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the Minimized-Expand State of Tile 2.
        /// </summary>
        public static string LayoutAndBehavior_ChangeTileStates_ConfigArea_MinimizeExpandButton {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_ChangeTileStates_ConfigArea_MinimizeExpandButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Area.
        /// </summary>
        public static string LayoutAndBehavior_ChangeTileStates_Tile_DefaultContent {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_ChangeTileStates_Tile_DefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 1.
        /// </summary>
        public static string LayoutAndBehavior_ChangeTileStates_Tile_Header1 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_ChangeTileStates_Tile_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 2.
        /// </summary>
        public static string LayoutAndBehavior_ChangeTileStates_Tile_Header2 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_ChangeTileStates_Tile_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 3.
        /// </summary>
        public static string LayoutAndBehavior_ChangeTileStates_Tile_Header3 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_ChangeTileStates_Tile_Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 4.
        /// </summary>
        public static string LayoutAndBehavior_ChangeTileStates_Tile_Header4 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_ChangeTileStates_Tile_Header4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Close Action.
        /// </summary>
        public static string LayoutAndBehavior_CloseTiles_ConfigArea_CloseActionLabel {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_CloseTiles_ConfigArea_CloseActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string LayoutAndBehavior_CloseTiles_ConfigArea_Header {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_CloseTiles_ConfigArea_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Hidden Tiles.
        /// </summary>
        public static string LayoutAndBehavior_CloseTiles_ConfigArea_ShowHiddenTilesLabel {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_CloseTiles_ConfigArea_ShowHiddenTilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapsible Tile.
        /// </summary>
        public static string LayoutAndBehavior_CloseTiles_Tile_Collapsible {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_CloseTiles_Tile_Collapsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 1.
        /// </summary>
        public static string LayoutAndBehavior_CloseTiles_Tile_Header1 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_CloseTiles_Tile_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 2.
        /// </summary>
        public static string LayoutAndBehavior_CloseTiles_Tile_Header2 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_CloseTiles_Tile_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 3.
        /// </summary>
        public static string LayoutAndBehavior_CloseTiles_Tile_Header3 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_CloseTiles_Tile_Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 4.
        /// </summary>
        public static string LayoutAndBehavior_CloseTiles_Tile_Header4 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_CloseTiles_Tile_Header4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Closable Tile.
        /// </summary>
        public static string LayoutAndBehavior_CloseTiles_Tile_NotClosable {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_CloseTiles_Tile_NotClosable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable Tile.
        /// </summary>
        public static string LayoutAndBehavior_CloseTiles_Tile_Removable {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_CloseTiles_Tile_Removable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Action Based on TileCloseAction.
        /// </summary>
        public static string LayoutAndBehavior_CloseTiles_Tile_TileCloseAction {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_CloseTiles_Tile_TileCloseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell:.
        /// </summary>
        public static string LayoutAndBehavior_DataBindingAndItemTemplates_MaxTemplate_CellLabel {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_DataBindingAndItemTemplates_MaxTemplate_CellLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string LayoutAndBehavior_DataBindingAndItemTemplates_MaxTemplate_PhoneLabel {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_DataBindingAndItemTemplates_MaxTemplate_PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand for Quick Contact Info.
        /// </summary>
        public static string LayoutAndBehavior_DataBindingAndItemTemplates_MinimizedTemplate_Text {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_DataBindingAndItemTemplates_MinimizedTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string LayoutAndBehavior_MaximizedTileLocation_ConfigArea_Header {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_MaximizedTileLocation_ConfigArea_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Location for Maximized Tiles.
        /// </summary>
        public static string LayoutAndBehavior_MaximizedTileLocation_ConfigArea_MaximizedTileLocation {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_MaximizedTileLocation_ConfigArea_MaximizedTileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Area.
        /// </summary>
        public static string LayoutAndBehavior_MaximizedTileLocation_Tile_DefaultContent {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_MaximizedTileLocation_Tile_DefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 1.
        /// </summary>
        public static string LayoutAndBehavior_MaximizedTileLocation_Tile_Header1 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_MaximizedTileLocation_Tile_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 2.
        /// </summary>
        public static string LayoutAndBehavior_MaximizedTileLocation_Tile_Header2 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_MaximizedTileLocation_Tile_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 3.
        /// </summary>
        public static string LayoutAndBehavior_MaximizedTileLocation_Tile_Header3 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_MaximizedTileLocation_Tile_Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 4.
        /// </summary>
        public static string LayoutAndBehavior_MaximizedTileLocation_Tile_Header4 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_MaximizedTileLocation_Tile_Header4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string LayoutAndBehavior_SavingAndLoadingLayouts_ConfigArea_Header {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_SavingAndLoadingLayouts_ConfigArea_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Layout.
        /// </summary>
        public static string LayoutAndBehavior_SavingAndLoadingLayouts_ConfigArea_LoadButton {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_SavingAndLoadingLayouts_ConfigArea_LoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Layout.
        /// </summary>
        public static string LayoutAndBehavior_SavingAndLoadingLayouts_ConfigArea_SaveButton {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_SavingAndLoadingLayouts_ConfigArea_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Image to Create a Tile.
        /// </summary>
        public static string LayoutAndBehavior_SavingAndLoadingLayouts_ConfigArea_TextLabel {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_SavingAndLoadingLayouts_ConfigArea_TextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample will not allow you to add duplicate images to xamTileManager.
        /// </summary>
        public static string LayoutAndBehavior_SavingAndLoadingLayouts_Options_Note {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_SavingAndLoadingLayouts_Options_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Area.
        /// </summary>
        public static string LayoutAndBehavior_TileConstraints_Tile_DefaultContent {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileConstraints_Tile_DefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 1.
        /// </summary>
        public static string LayoutAndBehavior_TileConstraints_Tile_Header1 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileConstraints_Tile_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 2.
        /// </summary>
        public static string LayoutAndBehavior_TileConstraints_Tile_Header2 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileConstraints_Tile_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 3.
        /// </summary>
        public static string LayoutAndBehavior_TileConstraints_Tile_Header3 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileConstraints_Tile_Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 4.
        /// </summary>
        public static string LayoutAndBehavior_TileConstraints_Tile_Header4 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileConstraints_Tile_Header4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Options.
        /// </summary>
        public static string LayoutAndBehavior_TileLayout_ConfigArea_Header {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileLayout_ConfigArea_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Layout Option.
        /// </summary>
        public static string LayoutAndBehavior_TileLayout_ConfigArea_LayoutOptionsLabel {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileLayout_ConfigArea_LayoutOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Area.
        /// </summary>
        public static string LayoutAndBehavior_TileLayout_Tile_DefaultContent {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileLayout_Tile_DefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 1.
        /// </summary>
        public static string LayoutAndBehavior_TileLayout_Tile_Header1 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileLayout_Tile_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 2.
        /// </summary>
        public static string LayoutAndBehavior_TileLayout_Tile_Header2 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileLayout_Tile_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 3.
        /// </summary>
        public static string LayoutAndBehavior_TileLayout_Tile_Header3 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileLayout_Tile_Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 4.
        /// </summary>
        public static string LayoutAndBehavior_TileLayout_Tile_Header4 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileLayout_Tile_Header4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 5.
        /// </summary>
        public static string LayoutAndBehavior_TileLayout_Tile_Header5 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileLayout_Tile_Header5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 6.
        /// </summary>
        public static string LayoutAndBehavior_TileLayout_Tile_Header6 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileLayout_Tile_Header6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 7.
        /// </summary>
        public static string LayoutAndBehavior_TileLayout_Tile_Header7 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileLayout_Tile_Header7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 8.
        /// </summary>
        public static string LayoutAndBehavior_TileLayout_Tile_Header8 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileLayout_Tile_Header8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 9.
        /// </summary>
        public static string LayoutAndBehavior_TileLayout_Tile_Header9 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileLayout_Tile_Header9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In VerticalVariable mode, 
        ///tiles 
        ///may not 
        ///align into 
        ///perfect rows..
        /// </summary>
        public static string LayoutAndBehavior_TileLayout_Tile_TallContent {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileLayout_Tile_TallContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In HorizontalVariable mode, tiles may not align into perfect columns..
        /// </summary>
        public static string LayoutAndBehavior_TileLayout_Tile_WideContent {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileLayout_Tile_WideContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Area.
        /// </summary>
        public static string LayoutAndBehavior_TileSettings_Tile_DefaultContent {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileSettings_Tile_DefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 1.
        /// </summary>
        public static string LayoutAndBehavior_TileSettings_Tile_Header1 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileSettings_Tile_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 2.
        /// </summary>
        public static string LayoutAndBehavior_TileSettings_Tile_Header2 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileSettings_Tile_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 3.
        /// </summary>
        public static string LayoutAndBehavior_TileSettings_Tile_Header3 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileSettings_Tile_Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile 4.
        /// </summary>
        public static string LayoutAndBehavior_TileSettings_Tile_Header4 {
            get {
                return ResourceManager.GetString("LayoutAndBehavior_TileSettings_Tile_Header4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme:.
        /// </summary>
        public static string ThemeSupport_ComboLabel {
            get {
                return ResourceManager.GetString("ThemeSupport_ComboLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ThemeSupport_DefaultTheme {
            get {
                return ResourceManager.GetString("ThemeSupport_DefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IG Theme.
        /// </summary>
        public static string ThemeSupport_IG {
            get {
                return ResourceManager.GetString("ThemeSupport_IG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Between Tiles.
        /// </summary>
        public static string XTM_SpaceBetweenTiles {
            get {
                return ResourceManager.GetString("XTM_SpaceBetweenTiles", resourceCulture);
            }
        }
    }
}
