<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Infragistics.Samples.Services</RootNamespace>
    <AssemblyName>Infragistics.Samples.Services</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <PreBuildEvent>taskkill /f /fi "pid gt 0" /im Infragistics.SamplesBrowser.exe</PreBuildEvent>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <DefineConstants>DEBUG;TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\Output\</OutputPath>
    <DefineConstants>DEBUG;TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\Output\</OutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <OutputPath>bin\x86\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE;WPF</DefineConstants>
    <CodeAnalysisLogFile>bin\DebugWPF\Infragistics.Samples.Services.dll.CodeAnalysisLog.xml</CodeAnalysisLogFile>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisRuleSetDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\\Rule Sets</CodeAnalysisRuleSetDirectories>
    <CodeAnalysisIgnoreBuiltInRuleSets>true</CodeAnalysisIgnoreBuiltInRuleSets>
    <CodeAnalysisRuleDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\FxCop\\Rules</CodeAnalysisRuleDirectories>
    <CodeAnalysisIgnoreBuiltInRules>true</CodeAnalysisIgnoreBuiltInRules>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>bin\x86\Release\</OutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
    <CodeAnalysisLogFile>bin\ReleaseWPF\Infragistics.Samples.Services.dll.CodeAnalysisLog.xml</CodeAnalysisLogFile>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisRuleSetDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\\Rule Sets</CodeAnalysisRuleSetDirectories>
    <CodeAnalysisIgnoreBuiltInRuleSets>true</CodeAnalysisIgnoreBuiltInRuleSets>
    <CodeAnalysisRuleDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\FxCop\\Rules</CodeAnalysisRuleDirectories>
    <CodeAnalysisIgnoreBuiltInRules>true</CodeAnalysisIgnoreBuiltInRules>
  </PropertyGroup>
  <ItemGroup>
    <Page Update="Controls\BrushPaletteSelector.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Infragistics.WPF.Charts.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.DataVisualization.Trial" Version="25.1.117" />
    <PackageReference Include="CoreWCF.Primitives" Version="1.8.0" />
    <PackageReference Include="CoreWCF.ConfigurationManager" Version="1.8.0" />
    <PackageReference Include="CoreWCF.Http" Version="1.8.0" />
    <PackageReference Include="CoreWCF.WebHttp" Version="1.8.0" />
    <PackageReference Include="CoreWCF.NetTcp" Version="1.8.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\hawaii-big-island.dbf" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\hawaii-big-island.prj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\hawaii-big-island.shp" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\north_america_primary_roads.dbf" />
    <Resource Include="Shapefiles\America\north_america_primary_roads.txt" />
    <Resource Include="Shapefiles\America\usa_counties_mod.txt" />
    <Resource Include="Shapefiles\America\usa_states_mod.txt" />
    <Resource Include="Shapefiles\America\usa_urban_areas_mod.txt" />
    <Resource Include="Shapefiles\World\earthquakes-usgs.txt" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\north_america_primary_roads.shp" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\north_america_primary_roads.shx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_counties_mod.dbf" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_counties_mod.shp" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_counties_mod.shx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_regions_group.dbf" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_regions_group.shp" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_regions_group.shx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_states_group.dbf" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_states_group.shp" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_states_group.shx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_states_mod.dbf" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_states_mod.shp" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_states_mod.shx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_urban_areas_mod.dbf" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_urban_areas_mod.shp" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\America\usa_urban_areas_mod.shx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110814.dbf" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110814.prj" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110814.shp" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110814.shx" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110821.dbf" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110821.prj" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110821.shp" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110821.shx" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110828.dbf" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110828.prj" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110828.shp" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110828.shx" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110904.dbf" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110904.prj" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110904.shp" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110904.shx" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110911.dbf" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110911.prj" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110911.shp" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110911.shx" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110925.dbf" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110925.prj" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110925.shp" />
    <Resource Include="Shapefiles\Weather\SeaSurfaceTemp\sst_20110925.shx" />
    <Resource Include="Shapefiles\World\world-cities.dbf" />
    <Resource Include="Shapefiles\World\world-cities.prj" />
    <Resource Include="Shapefiles\World\world-cities.shp" />
    <Resource Include="Shapefiles\World\world-cities.shx" />
    <Resource Include="Shapefiles\World\world_continents_small.dbf" />
    <Resource Include="Shapefiles\World\world_continents_small.shp" />
    <Resource Include="Shapefiles\World\world_continents_small.shx" />
    <Resource Include="Shapefiles\World\world_countries.dbf" />
    <Resource Include="Shapefiles\World\world_countries.shp" />
    <Resource Include="Shapefiles\World\world_countries.shx" />
    <Resource Include="Shapefiles\World\world_countries_reg.dbf" />
    <Resource Include="Shapefiles\World\world_countries_reg.README" />
    <Resource Include="Shapefiles\World\world_countries_reg.shp" />
    <Resource Include="Shapefiles\World\world_countries_reg.shx" />
    <Resource Include="Shapefiles\World\earthquakes-usgs.dbf" />
    <Resource Include="Shapefiles\World\earthquakes-usgs.shp" />
    <Resource Include="Shapefiles\World\earthquakes-usgs.shx" />
  </ItemGroup>
</Project>