<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Infragistics.Samples.Shared</RootNamespace>
    <AssemblyName>Infragistics.Samples.Shared</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <PreBuildEvent>taskkill /f /fi "pid gt 0" /im Infragistics.SamplesBrowser.exe</PreBuildEvent>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <DefineConstants>DEBUG;TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\Output\</OutputPath>
    <DefineConstants>DEBUG;TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\Output\</OutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <OutputPath>bin\x86\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE;WPF</DefineConstants>
    <CodeAnalysisLogFile>bin\DebugWPF\Infragistics.Samples.Shared.dll.CodeAnalysisLog.xml</CodeAnalysisLogFile>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisRuleSetDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\\Rule Sets</CodeAnalysisRuleSetDirectories>
    <CodeAnalysisIgnoreBuiltInRuleSets>true</CodeAnalysisIgnoreBuiltInRuleSets>
    <CodeAnalysisRuleDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\FxCop\\Rules</CodeAnalysisRuleDirectories>
    <CodeAnalysisIgnoreBuiltInRules>true</CodeAnalysisIgnoreBuiltInRules>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>bin\x86\Release\</OutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
    <CodeAnalysisLogFile>bin\ReleaseWPF\Infragistics.Samples.Shared.dll.CodeAnalysisLog.xml</CodeAnalysisLogFile>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisRuleSetDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\\Rule Sets</CodeAnalysisRuleSetDirectories>
    <CodeAnalysisIgnoreBuiltInRuleSets>true</CodeAnalysisIgnoreBuiltInRuleSets>
    <CodeAnalysisRuleDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\FxCop\\Rules</CodeAnalysisRuleDirectories>
    <CodeAnalysisIgnoreBuiltInRules>true</CodeAnalysisIgnoreBuiltInRules>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Infragistics.WPF.Themes.IG.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Themes.Metro.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Themes.MetroDark.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Themes.Office2010Blue.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Themes.Office2013.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Themes.RoyalDark.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Themes.RoyalLight.Trial" Version="25.1.117" />
    <PackageReference Include="System.Data.OleDb" Version="10.0.0-rc.2.25502.107" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Fonts\segoeui.ttf" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Models\DataChart\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Assets\Infragistics.Samples.Assets.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Controls\ColorPickerDialog.ico" />
  </ItemGroup>
</Project>