//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGContextMenu.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MenuStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGContextMenu.Resources.MenuStrings", typeof(MenuStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        public static string CM_Click_Here {
            get {
                return ResourceManager.GetString("CM_Click_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop (create shortcut).
        /// </summary>
        public static string CM_Menu_Desktop_Create_Shortcut {
            get {
                return ResourceManager.GetString("CM_Menu_Desktop_Create_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Recipient.
        /// </summary>
        public static string CM_Menu_Fax_Recipient {
            get {
                return ResourceManager.GetString("CM_Menu_Fax_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string CM_Menu_Item_1 {
            get {
                return ResourceManager.GetString("CM_Menu_Item_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distort.
        /// </summary>
        public static string CM_Menu_Item_10 {
            get {
                return ResourceManager.GetString("CM_Menu_Item_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand/Collapse.
        /// </summary>
        public static string CM_Menu_Item_2 {
            get {
                return ResourceManager.GetString("CM_Menu_Item_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string CM_Menu_Item_3 {
            get {
                return ResourceManager.GetString("CM_Menu_Item_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string CM_Menu_Item_4 {
            get {
                return ResourceManager.GetString("CM_Menu_Item_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string CM_Menu_Item_5 {
            get {
                return ResourceManager.GetString("CM_Menu_Item_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To.
        /// </summary>
        public static string CM_Menu_Item_6 {
            get {
                return ResourceManager.GetString("CM_Menu_Item_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Transform.
        /// </summary>
        public static string CM_Menu_Item_7 {
            get {
                return ResourceManager.GetString("CM_Menu_Item_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string CM_Menu_Item_8 {
            get {
                return ResourceManager.GetString("CM_Menu_Item_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skew.
        /// </summary>
        public static string CM_Menu_Item_9 {
            get {
                return ResourceManager.GetString("CM_Menu_Item_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Recipient.
        /// </summary>
        public static string CM_Menu_Mail_Recipient {
            get {
                return ResourceManager.GetString("CM_Menu_Mail_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message appears only when you click Menu Item 1.
        /// </summary>
        public static string CM_MenuItem1Clicked {
            get {
                return ResourceManager.GetString("CM_MenuItem1Clicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier keys for the opening action:.
        /// </summary>
        public static string CM_OB_ModifierKeys {
            get {
                return ResourceManager.GetString("CM_OB_ModifierKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action opening the menu:.
        /// </summary>
        public static string CM_OB_OpenMode {
            get {
                return ResourceManager.GetString("CM_OB_OpenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement:.
        /// </summary>
        public static string CM_Positioning_Placement {
            get {
                return ResourceManager.GetString("CM_Positioning_Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacementTarget:.
        /// </summary>
        public static string CM_Positioning_PlacementTarget {
            get {
                return ResourceManager.GetString("CM_Positioning_PlacementTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string CM_Positioning_PlacementTarget_None {
            get {
                return ResourceManager.GetString("CM_Positioning_PlacementTarget_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small blue rectangle.
        /// </summary>
        public static string CM_Positioning_PlacementTarget_SmallRect {
            get {
                return ResourceManager.GetString("CM_Positioning_PlacementTarget_SmallRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Click Here.
        /// </summary>
        public static string CM_Right_Click_Here {
            get {
                return ResourceManager.GetString("CM_Right_Click_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have just clicked .
        /// </summary>
        public static string CM_YouHaveJustClicked {
            get {
                return ResourceManager.GetString("CM_YouHaveJustClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have clicked a menu item..
        /// </summary>
        public static string CM_YouHaveJustClickedAMenuItem {
            get {
                return ResourceManager.GetString("CM_YouHaveJustClickedAMenuItem", resourceCulture);
            }
        }
    }
}
