<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <OutputPath>..\Output\</OutputPath>
    <ImplicitUsings>enable</ImplicitUsings>
    <PreBuildEvent>taskkill /f /fi "pid gt 0" /im Infragistics.SamplesBrowser.exe</PreBuildEvent>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Infragistics.WPF.Charts.Trial" Version="25.2.24" />
    <PackageReference Include="Infragistics.WPF.DataVisualization.Trial" Version="25.2.24" />
    <PackageReference Include="CoreWCF.Primitives" Version="1.8.0" />
    <PackageReference Include="CoreWCF.ConfigurationManager" Version="1.8.0" />
    <PackageReference Include="CoreWCF.Http" Version="1.8.0" />
    <PackageReference Include="CoreWCF.WebHttp" Version="1.8.0" />
    <PackageReference Include="CoreWCF.NetTcp" Version="1.8.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Assets\Infragistics.Samples.Assets.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Services\Infragistics.Samples.Services.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\airplane-seats.dbf" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\airplane-seats.shp" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\airplane-shape.dbf" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\airplane-shape.shp" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\world-countries.dbf" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\world-countries.shp" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\world-countries.shx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\world-airports.dbf" />
    <Resource Include="Shapefiles\world-airports.prj" />
    <Resource Include="Shapefiles\world-airports.shp" />
    <Resource Include="Shapefiles\world-airports.shx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\hospital_beds.dbf" />
    <Resource Include="Shapefiles\hospital_beds.shp" />
    <Resource Include="Shapefiles\hospital_beds.shx" />
    <Resource Include="Shapefiles\hospital_equipment.dbf" />
    <Resource Include="Shapefiles\hospital_equipment.shp" />
    <Resource Include="Shapefiles\hospital_equipment.shx" />
    <Resource Include="Shapefiles\hospital_items.dbf" />
    <Resource Include="Shapefiles\hospital_items.shp" />
    <Resource Include="Shapefiles\hospital_items.shx" />
    <Resource Include="Shapefiles\hospital_rooms.dbf" />
    <Resource Include="Shapefiles\hospital_rooms.shp" />
    <Resource Include="Shapefiles\hospital_rooms.shx" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Shapefiles\WorldCities.dbf" />
    <Resource Include="Shapefiles\WorldCities.shp" />
    <Resource Include="Shapefiles\WorldCities.shx" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Samples\ScatterCharts\Display\" />
  </ItemGroup>
</Project>