//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGExcel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExcelStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ExcelStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGExcel.Resources.ExcelStrings", typeof(ExcelStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not export the content to a file named:
        ///{0}
        ///Such file already exists and it is in use..
        /// </summary>
        public static string ErrMsg_FileAlreadyExistsAndInUse {
            get {
                return ResourceManager.GetString("ErrMsg_FileAlreadyExistsAndInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open password is invalid.
        /// </summary>
        public static string ErrMsg_OpenPasswordIsInvalid {
            get {
                return ResourceManager.GetString("ErrMsg_OpenPasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string Excel_ButtonCaptionExport {
            get {
                return ResourceManager.GetString("Excel_ButtonCaptionExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string Excel_ButtonCaptionImport {
            get {
                return ResourceManager.GetString("Excel_ButtonCaptionImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Comment.
        /// </summary>
        public static string Excel_Cell_Comment {
            get {
                return ResourceManager.GetString("Excel_Cell_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Formula.
        /// </summary>
        public static string Excel_Cell_Formula {
            get {
                return ResourceManager.GetString("Excel_Cell_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Excel_Discount {
            get {
                return ResourceManager.GetString("Excel_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format String.
        /// </summary>
        public static string Excel_Format_String {
            get {
                return ResourceManager.GetString("Excel_Format_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Excel_Quantity {
            get {
                return ResourceManager.GetString("Excel_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Comment.
        /// </summary>
        public static string Excel_Set_Comment {
            get {
                return ResourceManager.GetString("Excel_Set_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Formula.
        /// </summary>
        public static string Excel_Set_Formula {
            get {
                return ResourceManager.GetString("Excel_Set_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Excel_Total {
            get {
                return ResourceManager.GetString("Excel_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Excel_Unit_Price {
            get {
                return ResourceManager.GetString("Excel_Unit_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel XLS file format.
        /// </summary>
        public static string ExcelEngine_Combo_XLS {
            get {
                return ResourceManager.GetString("ExcelEngine_Combo_XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel 2007 XLSX file format.
        /// </summary>
        public static string ExcelEngine_Combo_XLSX {
            get {
                return ResourceManager.GetString("ExcelEngine_Combo_XLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ExcelEngine_DataGrid_Category {
            get {
                return ResourceManager.GetString("ExcelEngine_DataGrid_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Back Order.
        /// </summary>
        public static string ExcelEngine_DataGrid_OnBackOrder {
            get {
                return ResourceManager.GetString("ExcelEngine_DataGrid_OnBackOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ExcelEngine_DataGrid_ProductName {
            get {
                return ResourceManager.GetString("ExcelEngine_DataGrid_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Per Unit.
        /// </summary>
        public static string ExcelEngine_DataGrid_QuantityPerUnit {
            get {
                return ResourceManager.GetString("ExcelEngine_DataGrid_QuantityPerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        public static string ExcelEngine_DataGrid_SKU {
            get {
                return ResourceManager.GetString("ExcelEngine_DataGrid_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string ExcelEngine_DataGrid_Supplier {
            get {
                return ResourceManager.GetString("ExcelEngine_DataGrid_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string ExcelEngine_DataGrid_UnitPrice {
            get {
                return ResourceManager.GetString("ExcelEngine_DataGrid_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units In Stck.
        /// </summary>
        public static string ExcelEngine_DataGrid_UnitsInStock {
            get {
                return ResourceManager.GetString("ExcelEngine_DataGrid_UnitsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Excel Format.
        /// </summary>
        public static string ExcelEngine_OptionsLabel {
            get {
                return ResourceManager.GetString("ExcelEngine_OptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password used for file modification.
        /// </summary>
        public static string ExcelEngine_PasswordToFileWriteLabel {
            get {
                return ResourceManager.GetString("ExcelEngine_PasswordToFileWriteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password used to open the file.
        /// </summary>
        public static string ExcelEngine_PasswordToOpenLabel {
            get {
                return ResourceManager.GetString("ExcelEngine_PasswordToOpenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond with text.
        /// </summary>
        public static string ExcelShapes_Diamod {
            get {
                return ResourceManager.GetString("ExcelShapes_Diamod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text inside.
        /// </summary>
        public static string ExcelShapes_Diamod_InsideText {
            get {
                return ResourceManager.GetString("ExcelShapes_Diamod_InsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string ExcelShapes_Line {
            get {
                return ResourceManager.GetString("ExcelShapes_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string ExcelShapes_Rectangle {
            get {
                return ResourceManager.GetString("ExcelShapes_Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose shapes to export.
        /// </summary>
        public static string ExcelShapes_ShapesToExport {
            get {
                return ResourceManager.GetString("ExcelShapes_ShapesToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes Sheet.
        /// </summary>
        public static string ExcelShapes_SheetName {
            get {
                return ResourceManager.GetString("ExcelShapes_SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Data is filtered, then exported from the XamDataGrid to an xls or xlsx file. See C# code for more details..
        /// </summary>
        public static string ExportToExcel_Filter_Note {
            get {
                return ResourceManager.GetString("ExportToExcel_Filter_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Displaying Exported Workbook.
        /// </summary>
        public static string ExportToExcel_Message_ExcelError_Caption {
            get {
                return ResourceManager.GetString("ExportToExcel_Message_ExcelError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered while trying to run Excel to display the exported Workbook (do you have Excel installed)).  System message: {0}.
        /// </summary>
        public static string ExportToExcel_Message_ExcelError_Text {
            get {
                return ResourceManager.GetString("ExportToExcel_Message_ExcelError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was encountered while trying to export to a file; it&apos;s possible the application does not have sufficient permissions.  System message: {0}.
        /// </summary>
        public static string ExportToExcel_Message_ExcelExportError_Text {
            get {
                return ResourceManager.GetString("ExportToExcel_Message_ExcelExportError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Completed.
        /// </summary>
        public static string ExportToExcel_Message_ExportCompleted_Caption {
            get {
                return ResourceManager.GetString("ExportToExcel_Message_ExportCompleted_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Export completed successfully. Excel will now be executed to display the exported Workbook..
        /// </summary>
        public static string ExportToExcel_Message_ExportCompleted_Text {
            get {
                return ResourceManager.GetString("ExportToExcel_Message_ExportCompleted_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creating Unique File Name For Exported Workbook.
        /// </summary>
        public static string ExportToExcel_Message_FileError_Caption {
            get {
                return ResourceManager.GetString("ExportToExcel_Message_FileError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a unique name in the current working folder for the exported Workbook file!.
        /// </summary>
        public static string ExportToExcel_Message_FileError_Text {
            get {
                return ResourceManager.GetString("ExportToExcel_Message_FileError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Data.
        /// </summary>
        public static string ImportFromExcel_BtnClearData {
            get {
                return ResourceManager.GetString("ImportFromExcel_BtnClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Data.
        /// </summary>
        public static string ImportFromExcel_BtnSortData {
            get {
                return ResourceManager.GetString("ImportFromExcel_BtnSortData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Data is imported from an xls or xlsx file embedded as a resource. See the C# code for more details..
        /// </summary>
        public static string ImportFromExcel_Note {
            get {
                return ResourceManager.GetString("ImportFromExcel_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Open the document.
        /// </summary>
        public static string ImportFromExcel_SaveAndOpen {
            get {
                return ResourceManager.GetString("ImportFromExcel_SaveAndOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above Average.
        /// </summary>
        public static string NamedTables_AboveAverage {
            get {
                return ResourceManager.GetString("NamedTables_AboveAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Average.
        /// </summary>
        public static string NamedTables_BelowAverage {
            get {
                return ResourceManager.GetString("NamedTables_BelowAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name.
        /// </summary>
        public static string NamedTables_ColumnName {
            get {
                return ResourceManager.GetString("NamedTables_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert this table to a range in generated file.
        /// </summary>
        public static string NamedTables_ConvertTableToRange {
            get {
                return ResourceManager.GetString("NamedTables_ConvertTableToRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export modifications.
        /// </summary>
        public static string NamedTables_ExportModifications {
            get {
                return ResourceManager.GetString("NamedTables_ExportModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string NamedTables_Filter {
            get {
                return ResourceManager.GetString("NamedTables_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        public static string NamedTables_Formula {
            get {
                return ResourceManager.GetString("NamedTables_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is.
        /// </summary>
        public static string NamedTables_HeaderCellGridInfo_01 {
            get {
                return ResourceManager.GetString("NamedTables_HeaderCellGridInfo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table column information. You can change sort direction and filter for each column..
        /// </summary>
        public static string NamedTables_HeaderCellGridInfo_02 {
            get {
                return ResourceManager.GetString("NamedTables_HeaderCellGridInfo_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string NamedTables_Label {
            get {
                return ResourceManager.GetString("NamedTables_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can load Excel named tables by using the Load tables button..
        /// </summary>
        public static string NamedTables_LoadExcelDescription {
            get {
                return ResourceManager.GetString("NamedTables_LoadExcelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load tables.
        /// </summary>
        public static string NamedTables_LoadTables {
            get {
                return ResourceManager.GetString("NamedTables_LoadTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, make sure that there is no open file with the name:.
        /// </summary>
        public static string NamedTables_MakeSureNoOpenFile {
            get {
                return ResourceManager.GetString("NamedTables_MakeSureNoOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No formula applied..
        /// </summary>
        public static string NamedTables_NoFormulaApplied {
            get {
                return ResourceManager.GetString("NamedTables_NoFormulaApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Applied.
        /// </summary>
        public static string NamedTables_NotApplied {
            get {
                return ResourceManager.GetString("NamedTables_NotApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show header cell information.
        /// </summary>
        public static string NamedTables_ShowHeaderCell {
            get {
                return ResourceManager.GetString("NamedTables_ShowHeaderCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show total row information.
        /// </summary>
        public static string NamedTables_ShowTotalRow {
            get {
                return ResourceManager.GetString("NamedTables_ShowTotalRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort condition.
        /// </summary>
        public static string NamedTables_SortCondition {
            get {
                return ResourceManager.GetString("NamedTables_SortCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string NamedTables_SortDirection_Ascending {
            get {
                return ResourceManager.GetString("NamedTables_SortDirection_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string NamedTables_SortDirection_Descending {
            get {
                return ResourceManager.GetString("NamedTables_SortDirection_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name:.
        /// </summary>
        public static string NamedTables_TableName {
            get {
                return ResourceManager.GetString("NamedTables_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table style:.
        /// </summary>
        public static string NamedTables_TableStyle {
            get {
                return ResourceManager.GetString("NamedTables_TableStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below you can find more detailed information about.
        /// </summary>
        public static string NamedTables_TotalRowGridInfo_01 {
            get {
                return ResourceManager.GetString("NamedTables_TotalRowGridInfo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total row labels, formulas and values..
        /// </summary>
        public static string NamedTables_TotalRowGridInfo_02 {
            get {
                return ResourceManager.GetString("NamedTables_TotalRowGridInfo_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total row is not visible for this table..
        /// </summary>
        public static string NamedTables_TotalRowNotVisible {
            get {
                return ResourceManager.GetString("NamedTables_TotalRowNotVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string NamedTables_Value {
            get {
                return ResourceManager.GetString("NamedTables_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year to date.
        /// </summary>
        public static string NamedTables_YearToDate {
            get {
                return ResourceManager.GetString("NamedTables_YearToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} color {1} and color {2} is used.
        /// </summary>
        public static string NewColorModel_Export_Description_Color_One_and_Two {
            get {
                return ResourceManager.GetString("NewColorModel_Export_Description_Color_One_and_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here Linear Gradient fill with.
        /// </summary>
        public static string NewColorModel_Export_Description_LinearGradient {
            get {
                return ResourceManager.GetString("NewColorModel_Export_Description_LinearGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here Pattern Fill with Background color {0}, pattern color {1} and fill pattern style {2} is used.
        /// </summary>
        public static string NewColorModel_Export_Description_PatternFill {
            get {
                return ResourceManager.GetString("NewColorModel_Export_Description_PatternFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here Rectangular Gradient fill with .
        /// </summary>
        public static string NewColorModel_Export_Description_RectangularGradient {
            get {
                return ResourceManager.GetString("NewColorModel_Export_Description_RectangularGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here Solid Fill with color {0}  and a tint value {1} is used..
        /// </summary>
        public static string NewColorModel_Export_Description_SolidColorFill {
            get {
                return ResourceManager.GetString("NewColorModel_Export_Description_SolidColorFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Please, make sure that there is no open file with the name: {0}&quot;.
        /// </summary>
        public static string NewColorModel_Export_WarningMessage {
            get {
                return ResourceManager.GetString("NewColorModel_Export_WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate file.
        /// </summary>
        public static string NewColorModel_Generate {
            get {
                return ResourceManager.GetString("NewColorModel_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can specify type and two colors of the gradient brush. Cells in region A8:B9 in generated excel file will be filled according your choices..
        /// </summary>
        public static string NewColorModel_GradientFillDescription {
            get {
                return ResourceManager.GetString("NewColorModel_GradientFillDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient fill options:.
        /// </summary>
        public static string NewColorModel_GradientFillOptions {
            get {
                return ResourceManager.GetString("NewColorModel_GradientFillOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can specify background color, patter fill color and pattern type. Cells in region A5:B6 in generated file will be filled according your choices..
        /// </summary>
        public static string NewColorModel_PatternFillDescription {
            get {
                return ResourceManager.GetString("NewColorModel_PatternFillDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Fill options:.
        /// </summary>
        public static string NewColorModel_PatternFillOptions {
            get {
                return ResourceManager.GetString("NewColorModel_PatternFillOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Background Color:.
        /// </summary>
        public static string NewColorModel_SelectBackgroundColor {
            get {
                return ResourceManager.GetString("NewColorModel_SelectBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Gradient Color #1:.
        /// </summary>
        public static string NewColorModel_SelectGradientColorNo1 {
            get {
                return ResourceManager.GetString("NewColorModel_SelectGradientColorNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Gradient Color #2:.
        /// </summary>
        public static string NewColorModel_SelectGradientColorNo2 {
            get {
                return ResourceManager.GetString("NewColorModel_SelectGradientColorNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Gradient type: .
        /// </summary>
        public static string NewColorModel_SelectGradientType {
            get {
                return ResourceManager.GetString("NewColorModel_SelectGradientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Pattern Color:.
        /// </summary>
        public static string NewColorModel_SelectPatternColor {
            get {
                return ResourceManager.GetString("NewColorModel_SelectPatternColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Pattern Type:.
        /// </summary>
        public static string NewColorModel_SelectPatternType {
            get {
                return ResourceManager.GetString("NewColorModel_SelectPatternType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Solid Color: .
        /// </summary>
        public static string NewColorModel_SelectSolidColor {
            get {
                return ResourceManager.GetString("NewColorModel_SelectSolidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tint: .
        /// </summary>
        public static string NewColorModel_SelectTint {
            get {
                return ResourceManager.GetString("NewColorModel_SelectTint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can specify color to fill cells background and tint of this color. Cells in region A2:B3 in generated file will be filled with specified color and specified tint will be applied..
        /// </summary>
        public static string NewColorModel_SolidColorAndTintDescription {
            get {
                return ResourceManager.GetString("NewColorModel_SolidColorAndTintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Color Fill options:.
        /// </summary>
        public static string NewColorModel_SolidColorFillOptions {
            get {
                return ResourceManager.GetString("NewColorModel_SolidColorFillOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string XWG_Excel_ButtonCaptionExport {
            get {
                return ResourceManager.GetString("XWG_Excel_ButtonCaptionExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admittance Date.
        /// </summary>
        public static string XWG_Patient_AdmittanceDate {
            get {
                return ResourceManager.GetString("XWG_Patient_AdmittanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string XWG_Patient_DOB {
            get {
                return ResourceManager.GetString("XWG_Patient_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string XWG_Patient_FirstName {
            get {
                return ResourceManager.GetString("XWG_Patient_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string XWG_Patient_Gender {
            get {
                return ResourceManager.GetString("XWG_Patient_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string XWG_Patient_LastName {
            get {
                return ResourceManager.GetString("XWG_Patient_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string XWG_Patient_Location {
            get {
                return ResourceManager.GetString("XWG_Patient_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        public static string XWG_Patient_Severity {
            get {
                return ResourceManager.GetString("XWG_Patient_Severity", resourceCulture);
            }
        }
    }
}
