//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGDataTree.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataTreeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public DataTreeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGDataTree.Resources.DataTreeStrings", typeof(DataTreeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        public static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string DT_Category {
            get {
                return ResourceManager.GetString("DT_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre:.
        /// </summary>
        public static string DT_Genre {
            get {
                return ResourceManager.GetString("DT_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string Isbn {
            get {
                return ResourceManager.GetString("Isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents.
        /// </summary>
        public static string Parents {
            get {
                return ResourceManager.GetString("Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Node.
        /// </summary>
        public static string XDT_ActiveNode {
            get {
                return ResourceManager.GetString("XDT_ActiveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveNodeChanged Event.
        /// </summary>
        public static string XDT_ActiveNodeChanged {
            get {
                return ResourceManager.GetString("XDT_ActiveNodeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string XDT_Book {
            get {
                return ResourceManager.GetString("XDT_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string XDT_Button_Clear {
            get {
                return ResourceManager.GetString("XDT_Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        public static string XDT_Chapter {
            get {
                return ResourceManager.GetString("XDT_Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Tristate.
        /// </summary>
        public static string XDT_CheckBoxes_EnableTristate {
            get {
                return ResourceManager.GetString("XDT_CheckBoxes_EnableTristate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string XDT_CollapseAll {
            get {
                return ResourceManager.GetString("XDT_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DragEnter Event.
        /// </summary>
        public static string XDT_DragEnter {
            get {
                return ResourceManager.GetString("XDT_DragEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DragLeave Event.
        /// </summary>
        public static string XDT_DragLeave {
            get {
                return ResourceManager.GetString("XDT_DragLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DragOver Event.
        /// </summary>
        public static string XDT_DragOver {
            get {
                return ResourceManager.GetString("XDT_DragOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Event.
        /// </summary>
        public static string XDT_Drop {
            get {
                return ResourceManager.GetString("XDT_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string XDT_Employees_Header {
            get {
                return ResourceManager.GetString("XDT_Employees_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Details.
        /// </summary>
        public static string XDT_EmployeesDetails_Header {
            get {
                return ResourceManager.GetString("XDT_EmployeesDetails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Deleting.
        /// </summary>
        public static string XDT_EnableDeleting {
            get {
                return ResourceManager.GetString("XDT_EnableDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Editing.
        /// </summary>
        public static string XDT_EnableEditing {
            get {
                return ResourceManager.GetString("XDT_EnableEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string XDT_Events_PanelHeader {
            get {
                return ResourceManager.GetString("XDT_Events_PanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string XDT_ExpandAll {
            get {
                return ResourceManager.GetString("XDT_ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEnterKeyEditingEnabled.
        /// </summary>
        public static string XDT_IsEnterKeyEditingEnabled {
            get {
                return ResourceManager.GetString("XDT_IsEnterKeyEditingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsF2EditingEnabled.
        /// </summary>
        public static string XDT_IsF2EditingEnabled {
            get {
                return ResourceManager.GetString("XDT_IsF2EditingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsOnNodeActiveEditingEnabled.
        /// </summary>
        public static string XDT_IsOnNodeActiveEditingEnabled {
            get {
                return ResourceManager.GetString("XDT_IsOnNodeActiveEditingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string XDT_Level {
            get {
                return ResourceManager.GetString("XDT_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        public static string XDT_Node {
            get {
                return ResourceManager.GetString("XDT_Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeCheckedChanged Event.
        /// </summary>
        public static string XDT_NodeCheckedChanged {
            get {
                return ResourceManager.GetString("XDT_NodeCheckedChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeDragCancel Event.
        /// </summary>
        public static string XDT_NodeDragCancel {
            get {
                return ResourceManager.GetString("XDT_NodeDragCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeDragDrop Event.
        /// </summary>
        public static string XDT_NodeDragDrop {
            get {
                return ResourceManager.GetString("XDT_NodeDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeDragEnd Event.
        /// </summary>
        public static string XDT_NodeDragEnd {
            get {
                return ResourceManager.GetString("XDT_NodeDragEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeDraggingStart Event.
        /// </summary>
        public static string XDT_NodeDraggingStart {
            get {
                return ResourceManager.GetString("XDT_NodeDraggingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeEnteredEditMode Event.
        /// </summary>
        public static string XDT_NodeEnteredEditMode {
            get {
                return ResourceManager.GetString("XDT_NodeEnteredEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeEnteringEditMode Event.
        /// </summary>
        public static string XDT_NodeEnteringEditMode {
            get {
                return ResourceManager.GetString("XDT_NodeEnteringEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeExitedEditMode Event.
        /// </summary>
        public static string XDT_NodeExitedEditMode {
            get {
                return ResourceManager.GetString("XDT_NodeExitedEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeExitingEditMode Event.
        /// </summary>
        public static string XDT_NodeExitingEditMode {
            get {
                return ResourceManager.GetString("XDT_NodeExitingEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeExpansionChanged Event.
        /// </summary>
        public static string XDT_NodeExpansionChanged {
            get {
                return ResourceManager.GetString("XDT_NodeExpansionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeExpansionChanging Event.
        /// </summary>
        public static string XDT_NodeExpansionChanging {
            get {
                return ResourceManager.GetString("XDT_NodeExpansionChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeLayoutAssigned Event.
        /// </summary>
        public static string XDT_NodeLayoutAssigned {
            get {
                return ResourceManager.GetString("XDT_NodeLayoutAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Type.
        /// </summary>
        public static string XDT_NodeSelection_NodeSelectionType {
            get {
                return ResourceManager.GetString("XDT_NodeSelection_NodeSelectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string XDT_None {
            get {
                return ResourceManager.GetString("XDT_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Node.
        /// </summary>
        public static string XDT_ParentNode {
            get {
                return ResourceManager.GetString("XDT_ParentNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a genre to see related books.
        /// </summary>
        public static string XDT_SampleNote {
            get {
                return ResourceManager.GetString("XDT_SampleNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Only Available Books.
        /// </summary>
        public static string XDT_SelectedItems_SelectAvailable {
            get {
                return ResourceManager.GetString("XDT_SelectedItems_SelectAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All with Health Insurance.
        /// </summary>
        public static string XDT_SelectedItems_SelectWithInsurance {
            get {
                return ResourceManager.GetString("XDT_SelectedItems_SelectWithInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Box Options.
        /// </summary>
        public static string XDT_UsingCheckBoxes {
            get {
                return ResourceManager.GetString("XDT_UsingCheckBoxes", resourceCulture);
            }
        }
    }
}
