<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>IGDataChart</RootNamespace>
    <AssemblyName>IGDataChart</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWPF>true</UseWPF>
    <PreBuildEvent>taskkill /f /fi "pid gt 0" /im Infragistics.SamplesBrowser.exe</PreBuildEvent>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Custom\Series\" />
    <PackageReference Include="Infragistics.WPF.Charts.Olap.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Charts.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.ColorPicker.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.DataManager.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.DataTree.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.DataVisualization.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.DragDrop.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Math.Calculators.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Math.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Olap.FlatData.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Olap.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.PivotGrid.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Slider.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.TileManager.Trial" Version="25.1.117" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="Samples\Styling\LegendStyling.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Assets\Infragistics.Samples.Assets.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Services\Infragistics.Samples.Services.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\imgDown.png" />
    <Resource Include="Images\imgRemove.png" />
    <Resource Include="Images\imgRight.png" />
    <Resource Include="Images\imgUp.png" />
  </ItemGroup>
</Project>