<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>IGSparkline</RootNamespace>
    <AssemblyName>IGSparkline</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWPF>true</UseWPF>
      <EnableDefaultPageItems>false</EnableDefaultPageItems>

  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
    <PackageReference Include="Infragistics.WPF.DataGrids.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.DataVisualization.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Editors.Trial" Version="25.1.117" />
    <PackageReference Include="Infragistics.WPF.Sparkline.Trial" Version="25.1.117" />
  </ItemGroup>
  <ItemGroup>
    <Page Include="Assets\**\*.xaml" />
    <Page Include="Samples\**\*.xaml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Assets\Infragistics.Samples.Assets.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
</Project>