<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>IGDragDropFramework</RootNamespace>
    <AssemblyName>IGDragDropFramework</AssemblyName>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Output\</OutputPath>
    <BaseIntermediateOutputPath>obj\WPF\</BaseIntermediateOutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Infragistics.WPF.DragDrop.Trial" Version="25.1.117" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infragistics.Samples.Framework\Infragistics.Samples.Framework.WPF.csproj" />
    <ProjectReference Include="..\Infragistics.Samples.Shared\Infragistics.Samples.Shared.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\CopyCursor.png" />
    <Resource Include="Images\DisabledCursor.png" />
    <Resource Include="Images\MoveCursor.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Texture01.jpg" />
    <Resource Include="Images\Texture010.jpg" />
    <Resource Include="Images\Texture011.jpg" />
    <Resource Include="Images\Texture012.jpg" />
    <Resource Include="Images\Texture013.jpg" />
    <Resource Include="Images\Texture014.jpg" />
    <Resource Include="Images\Texture02.jpg" />
    <Resource Include="Images\Texture03.jpg" />
    <Resource Include="Images\Texture04.jpg" />
    <Resource Include="Images\Texture05.jpg" />
    <Resource Include="Images\Texture06.jpg" />
    <Resource Include="Images\Texture07.jpg" />
    <Resource Include="Images\Texture08.jpg" />
    <Resource Include="Images\Texture09.jpg" />
  </ItemGroup>
</Project>