//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGDockManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DockManagerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public DockManagerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGDockManager.Resources.DockManagerStrings", typeof(DockManagerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Maximization of Float Windows.
        /// </summary>
        public static string AllowMaxFloat {
            get {
                return ResourceManager.GetString("AllowMaxFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Minimization of Float Windows.
        /// </summary>
        public static string AllowMinFloat {
            get {
                return ResourceManager.GetString("AllowMinFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Owned Windows.
        /// </summary>
        public static string AllowOwnedWindows {
            get {
                return ResourceManager.GetString("AllowOwnedWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ColAddress {
            get {
                return ResourceManager.GetString("ColAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string ColCity {
            get {
                return ResourceManager.GetString("ColCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string ColCompanyName {
            get {
                return ResourceManager.GetString("ColCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColContactName {
            get {
                return ResourceManager.GetString("ColContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string ColCustomerID {
            get {
                return ResourceManager.GetString("ColCustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string ColPhone {
            get {
                return ResourceManager.GetString("ColPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Layout.
        /// </summary>
        public static string Docking_BtnLoadLayout {
            get {
                return ResourceManager.GetString("Docking_BtnLoadLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Layout.
        /// </summary>
        public static string Docking_BtnSaveLayout {
            get {
                return ResourceManager.GetString("Docking_BtnSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Visibility in Pane Header.
        /// </summary>
        public static string Docking_BtnVisability_Desc {
            get {
                return ResourceManager.GetString("Docking_BtnVisability_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Button.
        /// </summary>
        public static string Docking_ButtonVisibility_Samp_XdmStartPage_CloseButtonVisibility_Header {
            get {
                return ResourceManager.GetString("Docking_ButtonVisibility_Samp_XdmStartPage_CloseButtonVisibility_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Visibility in Pane Header.
        /// </summary>
        public static string Docking_ButtonVisibility_Samp_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("Docking_ButtonVisibility_Samp_XdmStartPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Button.
        /// </summary>
        public static string Docking_ButtonVisibility_Samp_XdmStartPage_PinButtonVisibility_Header {
            get {
                return ResourceManager.GetString("Docking_ButtonVisibility_Samp_XdmStartPage_PinButtonVisibility_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Position Menu.
        /// </summary>
        public static string Docking_ButtonVisibility_Samp_XdmStartPage_WindowPositionMenuVisibility_Header {
            get {
                return ResourceManager.GetString("Docking_ButtonVisibility_Samp_XdmStartPage_WindowPositionMenuVisibility_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Docking Events Output.
        /// </summary>
        public static string Docking_ClearEventsOutput {
            get {
                return ResourceManager.GetString("Docking_ClearEventsOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Button.
        /// </summary>
        public static string Docking_CloseBtn {
            get {
                return ResourceManager.GetString("Docking_CloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close button visibility:.
        /// </summary>
        public static string Docking_CloseBtnVisibility {
            get {
                return ResourceManager.GetString("Docking_CloseBtnVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Docking_Configuration {
            get {
                return ResourceManager.GetString("Docking_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FloatingWindowDragMode:.
        /// </summary>
        public static string Docking_DragBehavior_Samp_XdmStartPage_FloatingWindowDragMode_Header {
            get {
                return ResourceManager.GetString("Docking_DragBehavior_Samp_XdmStartPage_FloatingWindowDragMode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Behavior.
        /// </summary>
        public static string Docking_DragBehavior_Samp_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("Docking_DragBehavior_Samp_XdmStartPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabItemDragBehavior:.
        /// </summary>
        public static string Docking_DragBehavior_Samp_XdmStartPage_TabItemDragBehavior_Header {
            get {
                return ResourceManager.GetString("Docking_DragBehavior_Samp_XdmStartPage_TabItemDragBehavior_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error List.
        /// </summary>
        public static string Docking_ErrorList {
            get {
                return ResourceManager.GetString("Docking_ErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The floating pane can be maximixed to the size of the Dock Manager or to the size of the root visual for your application..
        /// </summary>
        public static string Docking_FloatingMaximizeDesc {
            get {
                return ResourceManager.GetString("Docking_FloatingMaximizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Pane.
        /// </summary>
        public static string Docking_FloatingPane {
            get {
                return ResourceManager.GetString("Docking_FloatingPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Pane - Not dockable.
        /// </summary>
        public static string Docking_FloatingPaneNotDockable {
            get {
                return ResourceManager.GetString("Docking_FloatingPaneNotDockable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Float Left:.
        /// </summary>
        public static string Docking_FloatLeft {
            get {
                return ResourceManager.GetString("Docking_FloatLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float Top:.
        /// </summary>
        public static string Docking_FloatTop {
            get {
                return ResourceManager.GetString("Docking_FloatTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlyoutAnimation:.
        /// </summary>
        public static string Docking_FlyoutBehavior_Samp_XdmStartPage_FlyoutAnimation_Header {
            get {
                return ResourceManager.GetString("Docking_FlyoutBehavior_Samp_XdmStartPage_FlyoutAnimation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout Behavior.
        /// </summary>
        public static string Docking_FlyoutBehavior_Samp_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("Docking_FlyoutBehavior_Samp_XdmStartPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnpinnedTabHoverAction:.
        /// </summary>
        public static string Docking_FlyoutBehavior_Samp_XdmStartPage_UnpinnedTabHoverAction_Header {
            get {
                return ResourceManager.GetString("Docking_FlyoutBehavior_Samp_XdmStartPage_UnpinnedTabHoverAction_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse image files ....
        /// </summary>
        public static string Docking_FolderText {
            get {
                return ResourceManager.GetString("Docking_FolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Docking_History {
            get {
                return ResourceManager.GetString("Docking_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Browser.
        /// </summary>
        public static string Docking_ImageBrowser {
            get {
                return ResourceManager.GetString("Docking_ImageBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string Docking_ImageBrowserShort {
            get {
                return ResourceManager.GetString("Docking_ImageBrowserShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Preview.
        /// </summary>
        public static string Docking_ImagePreview {
            get {
                return ResourceManager.GetString("Docking_ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Docking_ImagePreviewShort {
            get {
                return ResourceManager.GetString("Docking_ImagePreviewShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG file [Readonly].
        /// </summary>
        public static string Docking_ImageText {
            get {
                return ResourceManager.GetString("Docking_ImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Slider.
        /// </summary>
        public static string Docking_ImgSlider {
            get {
                return ResourceManager.GetString("Docking_ImgSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout #.
        /// </summary>
        public static string Docking_Layout {
            get {
                return ResourceManager.GetString("Docking_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize Type.
        /// </summary>
        public static string Docking_MaximizeType {
            get {
                return ResourceManager.GetString("Docking_MaximizeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | New Active Pane:.
        /// </summary>
        public static string Docking_NewActivePane {
            get {
                return ResourceManager.GetString("Docking_NewActivePane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Opacity.
        /// </summary>
        public static string Docking_OpacitySlider {
            get {
                return ResourceManager.GetString("Docking_OpacitySlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Text File....
        /// </summary>
        public static string Docking_OpenFile {
            get {
                return ResourceManager.GetString("Docking_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Docking_Output {
            get {
                return ResourceManager.GetString("Docking_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaneClosing event is cancelled for: .
        /// </summary>
        public static string Docking_PaneClosingCancelled {
            get {
                return ResourceManager.GetString("Docking_PaneClosingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaneUnpinning event is cancelled for.
        /// </summary>
        public static string Docking_PaneUnpinningCancelled {
            get {
                return ResourceManager.GetString("Docking_PaneUnpinningCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Behavior.
        /// </summary>
        public static string Docking_PinBehavior {
            get {
                return ResourceManager.GetString("Docking_PinBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin/Unpin/Auto Hide the Content Panes in the Tab Group Pane to see how they behave..
        /// </summary>
        public static string Docking_PinBehaviorDesc {
            get {
                return ResourceManager.GetString("Docking_PinBehaviorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Button.
        /// </summary>
        public static string Docking_PinBtn {
            get {
                return ResourceManager.GetString("Docking_PinBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin button visibility:.
        /// </summary>
        public static string Docking_PinBtnVisibility {
            get {
                return ResourceManager.GetString("Docking_PinBtnVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Active Pane:.
        /// </summary>
        public static string Docking_PreviousActivePane {
            get {
                return ResourceManager.GetString("Docking_PreviousActivePane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Docking_Properties {
            get {
                return ResourceManager.GetString("Docking_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Explorer.
        /// </summary>
        public static string Docking_SolutionExplorer {
            get {
                return ResourceManager.GetString("Docking_SolutionExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page.
        /// </summary>
        public static string Docking_StartPage {
            get {
                return ResourceManager.GetString("Docking_StartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Docking_TabHeaderText {
            get {
                return ResourceManager.GetString("Docking_TabHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Explorer.
        /// </summary>
        public static string Docking_TeamExplorer {
            get {
                return ResourceManager.GetString("Docking_TeamExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a saved layout to load:.
        /// </summary>
        public static string Docking_TxtBlock_SelectLayout {
            get {
                return ResourceManager.GetString("Docking_TxtBlock_SelectLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpinned Tab Hover Action.
        /// </summary>
        public static string Docking_UnpinnedTabHoverAction {
            get {
                return ResourceManager.GetString("Docking_UnpinnedTabHoverAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a saved layout to load from the list..
        /// </summary>
        public static string Docking_Warning1 {
            get {
                return ResourceManager.GetString("Docking_Warning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Position Menu.
        /// </summary>
        public static string Docking_WinPosBtn {
            get {
                return ResourceManager.GetString("Docking_WinPosBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Position Menu Visibility: .
        /// </summary>
        public static string Docking_WinPosBtnVisibility {
            get {
                return ResourceManager.GetString("Docking_WinPosBtnVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Chart Settings.
        /// </summary>
        public static string DockingXamWebChart_Settings {
            get {
                return ResourceManager.GetString("DockingXamWebChart_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Window Drag Mode: .
        /// </summary>
        public static string FloatingWindowDragMode {
            get {
                return ResourceManager.GetString("FloatingWindowDragMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For this ContentPane:.
        /// </summary>
        public static string Header_ForThisContentPane {
            get {
                return ResourceManager.GetString("Header_ForThisContentPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Header_Options {
            get {
                return ResourceManager.GetString("Header_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look at the two floating windows. Use the checkboxed above to customize their behavior..
        /// </summary>
        public static string Instruction1 {
            get {
                return ResourceManager.GetString("Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizing the Content Pane Context Menu.
        /// </summary>
        public static string InteractingWithTheDockManager_CustomizingContentPaneContextMenu_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("InteractingWithTheDockManager_CustomizingContentPaneContextMenu_XdmStartPage_Head" +
                        "er", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizing the Document TabGroup Files Menu.
        /// </summary>
        public static string InteractingWithTheDockManager_CustomizingTabGroupFilesMenu_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("InteractingWithTheDockManager_CustomizingTabGroupFilesMenu_XdmStartPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag any pane into another TabGroupPane via the center indicator icon to see it disabled..
        /// </summary>
        public static string InteractingWithTheDockManager_DynamicallyDisableDropLocations_XdmStartPage_Description {
            get {
                return ResourceManager.GetString("InteractingWithTheDockManager_DynamicallyDisableDropLocations_XdmStartPage_Descri" +
                        "ption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled Drop LocationDisabled Drop Location.
        /// </summary>
        public static string InteractingWithTheDockManager_DynamicallyDisableDropLocations_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("InteractingWithTheDockManager_DynamicallyDisableDropLocations_XdmStartPage_Header" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IGDockManager;component/Images/DIDisable.png.
        /// </summary>
        public static string InteractingWithTheDockManager_DynamicallyDisableDropLocations_XdmStartPage_Image {
            get {
                return ResourceManager.GetString("InteractingWithTheDockManager_DynamicallyDisableDropLocations_XdmStartPage_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse For Document Content To Load....
        /// </summary>
        public static string InteractingWithTheDockManager_DynamicallyLoadDocumentContent_XdmStartPage_Button {
            get {
                return ResourceManager.GetString("InteractingWithTheDockManager_DynamicallyLoadDocumentContent_XdmStartPage_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for a document and load its content.
        /// </summary>
        public static string InteractingWithTheDockManager_DynamicallyLoadDocumentContent_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("InteractingWithTheDockManager_DynamicallyLoadDocumentContent_XdmStartPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Use This Sample.
        /// </summary>
        public static string InteractingWithTheDockManager_LoadingAndSavingLayouts_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("InteractingWithTheDockManager_LoadingAndSavingLayouts_XdmStartPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ContentPane at the bottom of the right dock area demonstrates how to exclude a particular ContentPane from the saved layout. It&apos;s &apos;SaveInLayout&apos; property is set to false and as a result it will not be saved in the layout and will not be repositioned to a previous location when a saved layout is reloaded.  Instead it is placed outside all other reloaded panes..
        /// </summary>
        public static string InteractingWithTheDockManager_LoadingAndSavingLayouts_XdmStartPage_Note {
            get {
                return ResourceManager.GetString("InteractingWithTheDockManager_LoadingAndSavingLayouts_XdmStartPage_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string InteractingWithTheDockManager_LoadingAndSavingLayouts_XdmStartPage_NoteCaption {
            get {
                return ResourceManager.GetString("InteractingWithTheDockManager_LoadingAndSavingLayouts_XdmStartPage_NoteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Layout.
        /// </summary>
        public static string InteractingWithTheDockManager_LoadingAndSavingLayouts_XdmStartPage_SaveButton {
            get {
                return ResourceManager.GetString("InteractingWithTheDockManager_LoadingAndSavingLayouts_XdmStartPage_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: This ContentPane has its SaveInLayout property set to False.  It will not be saved in the layout..
        /// </summary>
        public static string InteractingWithTheDockManager_LoadingAndSavingLayouts_XdmStartPage_SaveLayoutNote {
            get {
                return ResourceManager.GetString("InteractingWithTheDockManager_LoadingAndSavingLayouts_XdmStartPage_SaveLayoutNote" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Re-arrange some docked and/or floating windows and click &apos;Save Layout&apos;: .
        /// </summary>
        public static string InteractingWithTheDockManager_LoadingAndSavingLayouts_XdmStartPage_Step1 {
            get {
                return ResourceManager.GetString("InteractingWithTheDockManager_LoadingAndSavingLayouts_XdmStartPage_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Re-arrange some windows again and select a saved layout to load: .
        /// </summary>
        public static string InteractingWithTheDockManager_LoadingAndSavingLayouts_XdmStartPage_Step2 {
            get {
                return ResourceManager.GetString("InteractingWithTheDockManager_LoadingAndSavingLayouts_XdmStartPage_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Float Windows in Taskbar.
        /// </summary>
        public static string ShowFloatWindowsInTaskbar {
            get {
                return ResourceManager.GetString("ShowFloatWindowsInTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Glyphs.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomizeContentPaneGlyphs_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomizeContentPaneGlyphs_XdmStartPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IGDockManager;component/Images/CustomGlyphs.png.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomizeContentPaneGlyphs_XdmStartPage_Image {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomizeContentPaneGlyphs_XdmStartPage_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...drag any ContentPane into a dockable area..
        /// </summary>
        public static string ThemesAndCustomStyles_CustomizingDockPreviewArea_XdmStartPage_Description {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomizingDockPreviewArea_XdmStartPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To See Custom Dock Preview Areas....
        /// </summary>
        public static string ThemesAndCustomStyles_CustomizingDockPreviewArea_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomizingDockPreviewArea_XdmStartPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IGDockManager;component/Images/DropPreview.png.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomizingDockPreviewArea_XdmStartPage_Image {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomizingDockPreviewArea_XdmStartPage_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Description1 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  + .
        /// </summary>
        public static string ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Description2 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Description3 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Description4 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Description5 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Description5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  + .
        /// </summary>
        public static string ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Description6 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Description6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F7.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Description7 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Description7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl + Tab or Alt + F7 to see the PaneNavigator.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomizingPaneNavigator_XdmStartPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Wash Options.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Set WashMode.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseMode_Description_Text1 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseMode_Descript" +
                        "ion_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ResourceWasher provides two modes of alteration for you to choose from: HueSaturationReplacement or SoftLightBlend. Toggle between these two modes to see the difference..
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseMode_Description_Text2 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseMode_Descript" +
                        "ion_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WashMode:.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseMode_Description_Text3 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseMode_Descript" +
                        "ion_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Select Theme to Wash.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Description_Text1 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Descrip" +
                        "tion_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a theme for the ResourceWasher .
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Description_Text2 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Descrip" +
                        "tion_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to wash. Select from the list of included XamDockManager.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Description_Text3 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Descrip" +
                        "tion_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  themes. Two special themes were created .
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Description_Text4 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Descrip" +
                        "tion_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (DockManagerWashBaseDark and DockManagerWashBaseLight).
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Description_Text5 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Descrip" +
                        "tion_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  specifically for use by our external theme assemblies.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Description_Text6 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Descrip" +
                        "tion_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (i.e. Forest Green)..
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Description_Text7 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Descrip" +
                        "tion_Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Description_ThemeText {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashBaseTheme_Descrip" +
                        "tion_ThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Set WashColors.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashColors_Description_Text1 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashColors_Descriptio" +
                        "n_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the WashColor of each of the WashGroups listed below. Each WashGroup corresponds to a region or state within the Dock Manager. For even faster customization, you can set the ResourceWasher.WashColor property. That value is then applied to all WashGroups.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashColors_Description_Text2 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashColors_Descriptio" +
                        "n_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashColors_Description_Text3 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashColors_Descriptio" +
                        "n_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashColors_Description_Text4 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashColors_Descriptio" +
                        "n_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Color:.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashColors_Description_Text5 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashColors_Descriptio" +
                        "n_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set color.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashColors_Description_Text6 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashColors_Descriptio" +
                        "n_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Color:.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashColors_Description_Text7 {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesDynamic_Samp_XdmStartPage_WashColors_Descriptio" +
                        "n_Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample XAML Code.
        /// </summary>
        public static string ThemesAndCustomStyles_CustomThemesSimple_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_CustomThemesSimple_XdmStartPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...drag any ContentPane in this sample..
        /// </summary>
        public static string ThemesAndCustomStyles_DockIndicatorStyling_XdmStartPage_Description {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_DockIndicatorStyling_XdmStartPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To See Custom Docking Indicators....
        /// </summary>
        public static string ThemesAndCustomStyles_DockIndicatorStyling_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_DockIndicatorStyling_XdmStartPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IGDockManager;component/Images/DIDrag.png.
        /// </summary>
        public static string ThemesAndCustomStyles_DockIndicatorStyling_XdmStartPage_Image {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_DockIndicatorStyling_XdmStartPage_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting The Theme.
        /// </summary>
        public static string ThemesAndCustomStyles_SettingTheTheme_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("ThemesAndCustomStyles_SettingTheTheme_XdmStartPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string XamDockManager_Root_VS08_BottomEdge_Header1 {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_BottomEdge_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error List.
        /// </summary>
        public static string XamDockManager_Root_VS08_BottomEdge_Header2 {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_BottomEdge_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string XamDockManager_Root_VS08_BottomEdge_Header3 {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_BottomEdge_Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IGDockManager;component/Images/output.png.
        /// </summary>
        public static string XamDockManager_Root_VS08_BottomEdge_Image1 {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_BottomEdge_Image1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IGDockManager;component/Images/error.png.
        /// </summary>
        public static string XamDockManager_Root_VS08_BottomEdge_Image2 {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_BottomEdge_Image2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IGDockManager;component/Images/history.png.
        /// </summary>
        public static string XamDockManager_Root_VS08_BottomEdge_Image3 {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_BottomEdge_Image3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page.
        /// </summary>
        public static string XamDockManager_Root_VS08_Page1_Header {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_Page1_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window1.xaml.
        /// </summary>
        public static string XamDockManager_Root_VS08_Page2_Header {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_Page2_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window1.xaml.cs.
        /// </summary>
        public static string XamDockManager_Root_VS08_Page3_Header {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_Page3_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.xaml.
        /// </summary>
        public static string XamDockManager_Root_VS08_Page4_Header {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_Page4_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Explorer.
        /// </summary>
        public static string XamDockManager_Root_VS08_RightEdge_Header1 {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_RightEdge_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Explorer.
        /// </summary>
        public static string XamDockManager_Root_VS08_RightEdge_Header2 {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_RightEdge_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string XamDockManager_Root_VS08_RightEdge_Header3 {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_RightEdge_Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IGDockManager;component/Images/solution_explorer.png.
        /// </summary>
        public static string XamDockManager_Root_VS08_RightEdge_Image1 {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_RightEdge_Image1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IGDockManager;component/Images/team_explorer.png.
        /// </summary>
        public static string XamDockManager_Root_VS08_RightEdge_Image2 {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_RightEdge_Image2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IGDockManager;component/Images/properties.png.
        /// </summary>
        public static string XamDockManager_Root_VS08_RightEdge_Image3 {
            get {
                return ResourceManager.GetString("XamDockManager_Root_VS08_RightEdge_Image3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the Snippet tab for more information..
        /// </summary>
        public static string XamDockManager_SnippetTabInfo {
            get {
                return ResourceManager.GetString("XamDockManager_SnippetTabInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Edge Dock Content #1.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_BottomEdgeDockPane_Content1 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_BottomEdgeDockPane_Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Edge Dock Content #2.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_BottomEdgeDockPane_Content2 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_BottomEdgeDockPane_Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Edge Dock Content #3.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_BottomEdgeDockPane_Content3 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_BottomEdgeDockPane_Content3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Edge Dock Pane #1.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_BottomEdgeDockPane_Header1 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_BottomEdgeDockPane_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Edge Dock Pane #2.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_BottomEdgeDockPane_Header2 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_BottomEdgeDockPane_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Edge Dock Pane #3.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_BottomEdgeDockPane_Header3 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_BottomEdgeDockPane_Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Content #1.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_DocumentPane_Content1 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_DocumentPane_Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Content #2.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_DocumentPane_Content2 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_DocumentPane_Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Content #3.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_DocumentPane_Content3 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_DocumentPane_Content3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Content #4.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_DocumentPane_Content4 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_DocumentPane_Content4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Content #5.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_DocumentPane_Content5 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_DocumentPane_Content5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Content #6.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_DocumentPane_Content6 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_DocumentPane_Content6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Content #7.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_DocumentPane_Content7 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_DocumentPane_Content7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Pane #1.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_DocumentPane_Header1 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_DocumentPane_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Pane #2.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_DocumentPane_Header2 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_DocumentPane_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Pane #3.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_DocumentPane_Header3 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_DocumentPane_Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Pane #4.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_DocumentPane_Header4 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_DocumentPane_Header4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Pane #5.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_DocumentPane_Header5 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_DocumentPane_Header5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Pane #6.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_DocumentPane_Header6 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_DocumentPane_Header6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Pane #7.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_DocumentPane_Header7 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_DocumentPane_Header7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Dockable Pane #1.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_FloatingDockableDockPane_Header1 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_FloatingDockableDockPane_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Dockable Pane #2.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_FloatingDockableDockPane_Header2 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_FloatingDockableDockPane_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Dockable Content #1.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_FloatingDockablePane_Content1 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_FloatingDockablePane_Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Dockable Content #2.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_FloatingDockablePane_Content2 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_FloatingDockablePane_Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FloatingOnly Pane.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_FloatingOnlyDockPane_Header {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_FloatingOnlyDockPane_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FloatingOnly Content.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_FloatingOnlyPane_Content {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_FloatingOnlyPane_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Edge Dock Content.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_LeftEdgeDockPane_Content {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_LeftEdgeDockPane_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Edge Dock Content  (unpinned).
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_LeftEdgeDockPane_Content_UnPinned {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_LeftEdgeDockPane_Content_UnPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Edge Dock Pane.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_LeftEdgeDockPane_Header {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_LeftEdgeDockPane_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Edge Dock Pane (unpinned).
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_LeftEdgeDockPane_Header_UnPinned {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_LeftEdgeDockPane_Header_UnPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge Dock Content.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_RightEdgeDockPane_Content {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_RightEdgeDockPane_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge Dock Content (pinned).
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_RightEdgeDockPane_Content_Pinned {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_RightEdgeDockPane_Content_Pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge Dock Content #1.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_RightEdgeDockPane_Content1 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_RightEdgeDockPane_Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge Dock Content #2.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_RightEdgeDockPane_Content2 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_RightEdgeDockPane_Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge Dock Content #3.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_RightEdgeDockPane_Content3 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_RightEdgeDockPane_Content3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge Dock Content #4.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_RightEdgeDockPane_Content4 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_RightEdgeDockPane_Content4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge Dock Pane.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_RightEdgeDockPane_Header {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_RightEdgeDockPane_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge Dock Pane (pinned).
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_RightEdgeDockPane_Header_Pinned {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_RightEdgeDockPane_Header_Pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge Dock Pane #1.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_RightEdgeDockPane_Header1 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_RightEdgeDockPane_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge Dock Pane #2.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_RightEdgeDockPane_Header2 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_RightEdgeDockPane_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge Dock Pane #3.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_RightEdgeDockPane_Header3 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_RightEdgeDockPane_Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge Dock Pane #4.
        /// </summary>
        public static string XamDockManagerWalkthrough_Root_RightEdgeDockPane_Header4 {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_Root_RightEdgeDockPane_Header4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the XAML code to see how to add an Icon..
        /// </summary>
        public static string XamDockManagerWalkthrough_SpecifyIconsForContentPanes_XdmStartPage_Description {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_SpecifyIconsForContentPanes_XdmStartPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Icons for Content Panes.
        /// </summary>
        public static string XamDockManagerWalkthrough_SpecifyIconsForContentPanes_XdmStartPage_Header {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_SpecifyIconsForContentPanes_XdmStartPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IGDockManager;component/Images/IconsContentPanes.png.
        /// </summary>
        public static string XamDockManagerWalkthrough_SpecifyIconsForContentPanes_XdmStartPage_Image {
            get {
                return ResourceManager.GetString("XamDockManagerWalkthrough_SpecifyIconsForContentPanes_XdmStartPage_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowClose.
        /// </summary>
        public static string XdmDockingBehaviorOptionsControl_Description_CheckBox1 {
            get {
                return ResourceManager.GetString("XdmDockingBehaviorOptionsControl_Description_CheckBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowPinning.
        /// </summary>
        public static string XdmDockingBehaviorOptionsControl_Description_CheckBox2 {
            get {
                return ResourceManager.GetString("XdmDockingBehaviorOptionsControl_Description_CheckBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowDocking.
        /// </summary>
        public static string XdmDockingBehaviorOptionsControl_Description_CheckBox3 {
            get {
                return ResourceManager.GetString("XdmDockingBehaviorOptionsControl_Description_CheckBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowDockingInTabGroup.
        /// </summary>
        public static string XdmDockingBehaviorOptionsControl_Description_CheckBox4 {
            get {
                return ResourceManager.GetString("XdmDockingBehaviorOptionsControl_Description_CheckBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowFloatingOnly.
        /// </summary>
        public static string XdmDockingBehaviorOptionsControl_Description_CheckBox5 {
            get {
                return ResourceManager.GetString("XdmDockingBehaviorOptionsControl_Description_CheckBox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowInDocumentHost.
        /// </summary>
        public static string XdmDockingBehaviorOptionsControl_Description_CheckBox6 {
            get {
                return ResourceManager.GetString("XdmDockingBehaviorOptionsControl_Description_CheckBox6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string XWG_Grid_ProductCategory {
            get {
                return ResourceManager.GetString("XWG_Grid_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string XWG_Grid_ProductName {
            get {
                return ResourceManager.GetString("XWG_Grid_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        public static string XWG_Grid_ProductSKU {
            get {
                return ResourceManager.GetString("XWG_Grid_ProductSKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string XWG_Grid_UnitPrice {
            get {
                return ResourceManager.GetString("XWG_Grid_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units On Order.
        /// </summary>
        public static string XWG_Grid_UnitsOnOrder {
            get {
                return ResourceManager.GetString("XWG_Grid_UnitsOnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string XWG_Supplier {
            get {
                return ResourceManager.GetString("XWG_Supplier", resourceCulture);
            }
        }
    }
}
